const mongoose = require('mongoose')
const ObjectId = mongoose.Types.ObjectId

const AtecSchema = mongoose.Schema({
    atec_beneid :{ type: ObjectId, required: false },
    atec_benesexo :{ type: String, required: false },
    atec_datecnasc :{ type: String, required: false },
    atec_idade :{ type: String, required: false },
    atec_preenchido :{ type: String, required: false },
    atec_paren :{ type: String, required: false },
    atec_teraacompid :{ type: ObjectId, required: false },
    atec_infoiniatec :{ type: String, required: false },
    atec_concluido :{ type: String, required: false },
    atec_dataatec :{ type: String, required: false },
    //Totais
    atec_atec1Total :{ type: String, required: false },
    atec_atec2Total :{ type: String, required: false },
    atec_atec3Total :{ type: String, required: false },
    atec_atec4Total :{ type: String, required: false },
    atec_totpont :{ type: String, required: false },
    atec_comentatec :{ type: String, required: false },
    //Questionário I - 1
    atec_1q01 :{ type: String, required: false },
    atec_1q02 :{ type: String, required: false },
    atec_1q03 :{ type: String, required: false },
    atec_1q04 :{ type: String, required: false },
    atec_1q05 :{ type: String, required: false },
    atec_1q06 :{ type: String, required: false },
    atec_1q07 :{ type: String, required: false },
    atec_1q08 :{ type: String, required: false },
    atec_1q09 :{ type: String, required: false },
    atec_1q10 :{ type: String, required: false },
    atec_1q11 :{ type: String, required: false },
    atec_1q12 :{ type: String, required: false },
    atec_1q13 :{ type: String, required: false },
    atec_1q14 :{ type: String, required: false },
    // Questionário II - 2 
    atec_2q01 :{ type: String, required: false },
    atec_2q02 :{ type: String, required: false },
    atec_2q03 :{ type: String, required: false },
    atec_2q04 :{ type: String, required: false },
    atec_2q05 :{ type: String, required: false },
    atec_2q06 :{ type: String, required: false },
    atec_2q07 :{ type: String, required: false },
    atec_2q08 :{ type: String, required: false },
    atec_2q09 :{ type: String, required: false },
    atec_2q10 :{ type: String, required: false },
    atec_2q11 :{ type: String, required: false },
    atec_2q12 :{ type: String, required: false },
    atec_2q13 :{ type: String, required: false },
    atec_2q14 :{ type: String, required: false },
    atec_2q15 :{ type: String, required: false },
    atec_2q16 :{ type: String, required: false },
    atec_2q17 :{ type: String, required: false },
    atec_2q18 :{ type: String, required: false },
    atec_2q19 :{ type: String, required: false },
    atec_2q20 :{ type: String, required: false },
    // Questionário III - 3 
    atec_3q01 :{ type: String, required: false },
    atec_3q02 :{ type: String, required: false },
    atec_3q03 :{ type: String, required: false },
    atec_3q04 :{ type: String, required: false },
    atec_3q05 :{ type: String, required: false },
    atec_3q06 :{ type: String, required: false },
    atec_3q07 :{ type: String, required: false },
    atec_3q08 :{ type: String, required: false },
    atec_3q09 :{ type: String, required: false },
    atec_3q10 :{ type: String, required: false },
    atec_3q11 :{ type: String, required: false },
    atec_3q12 :{ type: String, required: false },
    atec_3q13 :{ type: String, required: false },
    atec_3q14 :{ type: String, required: false },
    atec_3q15 :{ type: String, required: false },
    atec_3q16 :{ type: String, required: false },
    atec_3q17 :{ type: String, required: false },
    atec_3q18 :{ type: String, required: false },
    // Questionário IV
    atec_4q01 :{ type: String, required: false },
    atec_4q02 :{ type: String, required: false },
    atec_4q03 :{ type: String, required: false },
    atec_4q04 :{ type: String, required: false },
    atec_4q05 :{ type: String, required: false },
    atec_4q06 :{ type: String, required: false },
    atec_4q07 :{ type: String, required: false },
    atec_4q08 :{ type: String, required: false },
    atec_4q09 :{ type: String, required: false },
    atec_4q10 :{ type: String, required: false },
    atec_4q11 :{ type: String, required: false },
    atec_4q12 :{ type: String, required: false },
    atec_4q13 :{ type: String, required: false },
    atec_4q14 :{ type: String, required: false },
    atec_4q15 :{ type: String, required: false },
    atec_4q16 :{ type: String, required: false },
    atec_4q17 :{ type: String, required: false },
    atec_4q18 :{ type: String, required: false },
    atec_4q19 :{ type: String, required: false },
    atec_4q20 :{ type: String, required: false },
    atec_4q21 :{ type: String, required: false },
    atec_4q22 :{ type: String, required: false },
    atec_4q23 :{ type: String, required: false },
    atec_4q24 :{ type: String, required: false },
    atec_4q25 :{ type: String, required: false },
    //Atributos de controle
    atec_usuidcad :{ type: ObjectId, required: false },
    atec_usuidedi :{ type: ObjectId, required: false },
    atec_datacad :{ type: String, required: false },
    atec_dataedi :{ type: String, required: false }
    
})

class Atec{
    constructor(
        atec_beneid,
        atec_benesexo,
        atec_datecnasc,
        atec_idade,
        atec_preenchido,
        atec_paren,
        atec_teraacompid,
        atec_infoiniatec,
        atec_concluido,
        atec_dataatec,
        //Totais
        atec_atec1Total,
        atec_atec2Total,
        atec_atec3Total,
        atec_atec4Total,
        atec_totpont,
        atec_comentatec,
        //Questionário I - 1
        atec_1q01,
        atec_1q02,
        atec_1q03,
        atec_1q04,
        atec_1q05,
        atec_1q06,
        atec_1q07,
        atec_1q08,
        atec_1q09,
        atec_1q10,
        atec_1q11,
        atec_1q12,
        atec_1q13,
        atec_1q14,
        // Questionário II - 2 
        atec_2q01,
        atec_2q02,
        atec_2q03,
        atec_2q04,
        atec_2q05,
        atec_2q06,
        atec_2q07,
        atec_2q08,
        atec_2q09,
        atec_2q10,
        atec_2q11,
        atec_2q12,
        atec_2q13,
        atec_2q14,
        atec_2q15,
        atec_2q16,
        atec_2q17,
        atec_2q18,
        atec_2q19,
        atec_2q20,
        // Questionário III - 3 
        atec_3q01,
        atec_3q02,
        atec_3q03,
        atec_3q04,
        atec_3q05,
        atec_3q06,
        atec_3q07,
        atec_3q08,
        atec_3q09,
        atec_3q10,
        atec_3q11,
        atec_3q12,
        atec_3q13,
        atec_3q14,
        atec_3q15,
        atec_3q16,
        atec_3q17,
        atec_3q18,
        // Questionário IV
        atec_4q01,
        atec_4q02,
        atec_4q03,
        atec_4q04,
        atec_4q05,
        atec_4q06,
        atec_4q07,
        atec_4q08,
        atec_4q09,
        atec_4q10,
        atec_4q11,
        atec_4q12,
        atec_4q13,
        atec_4q14,
        atec_4q15,
        atec_4q16,
        atec_4q17,
        atec_4q18,
        atec_4q19,
        atec_4q20,
        atec_4q21,
        atec_4q22,
        atec_4q23,
        atec_4q24,
        atec_4q25,
        //Atributos de controle
        atec_usuidcad,
        atec_usuidedi,
        atec_datacad,
        atec_dataedi
        ){
        this.atec_beneid = atec_beneid,
        this.atec_benesexo = atec_benesexo,
        this.atec_datecnasc = atec_datecnasc,
        this.atec_idade = atec_idade,
        this.atec_preenchido = atec_preenchido,
        this.atec_paren =  atec_paren,
        this.atec_teraacompid = atec_teraacompid,
        this.atec_infoiniatec = atec_infoiniatec,
        this.atec_concluido = atec_concluido,
        this.atec_dataatec = atec_dataatec,
        //Totais
        this.atec_atec1Total = atec_atec1Total,
        this.atec_atec2Total = atec_atec2Total,
        this.atec_atec3Total = atec_atec3Total,
        this.atec_atec4Total = atec_atec4Total,
        this.atec_totpont = atec_totpont,
        this.atec_comentatec = atec_comentatec,
        //Questionário I - 1
        this.atec_1q01 = atec_1q01,
        this.atec_1q02 = atec_1q02,
        this.atec_1q03 = atec_1q03,
        this.atec_1q04 = atec_1q04,
        this.atec_1q05 = atec_1q05,
        this.atec_1q06 = atec_1q06,
        this.atec_1q07 = atec_1q07,
        this.atec_1q08 = atec_1q08,
        this.atec_1q09 = atec_1q09,
        this.atec_1q10 = atec_1q10,
        this.atec_1q11 = atec_1q11,
        this.atec_1q12 = atec_1q12,
        this.atec_1q13 = atec_1q13,
        this.atec_1q14 = atec_1q14,
        // Questionário II - 2 
        this.atec_2q01 = atec_2q01,
        this.atec_2q02 = atec_2q02,
        this.atec_2q03 = atec_2q03,
        this.atec_2q04 = atec_2q04,
        this.atec_2q05 = atec_2q05,
        this.atec_2q06 = atec_2q06,
        this.atec_2q07 = atec_2q07,
        this.atec_2q08 = atec_2q08,
        this.atec_2q09 = atec_2q09,
        this.atec_2q10 = atec_2q10,
        this.atec_2q11 = atec_2q11,
        this.atec_2q12 = atec_2q12,
        this.atec_2q13 = atec_2q13,
        this.atec_2q14 = atec_2q14,
        this.atec_2q15 = atec_2q15,
        this.atec_2q16 = atec_2q16,
        this.atec_2q17 = atec_2q17,
        this.atec_2q18 = atec_2q18,
        this.atec_2q19 = atec_2q19,
        this.atec_2q20 = atec_2q20,
        // Questionário III - 3 
        this.atec_3q01 = atec_3q01,
        this.atec_3q02 = atec_3q02,
        this.atec_3q03 = atec_3q03,
        this.atec_3q04 = atec_3q04,
        this.atec_3q05 = atec_3q05,
        this.atec_3q06 = atec_3q06,
        this.atec_3q07 = atec_3q07,
        this.atec_3q08 = atec_3q08,
        this.atec_3q09 = atec_3q09,
        this.atec_3q10 = atec_3q10,
        this.atec_3q11 = atec_3q11,
        this.atec_3q12 = atec_3q12,
        this.atec_3q13 = atec_3q13,
        this.atec_3q14 = atec_3q14,
        this.atec_3q15 = atec_3q15,
        this.atec_3q16 = atec_3q16,
        this.atec_3q17 = atec_3q17,
        this.atec_3q18 = atec_3q18,
        // Questionário IV
        this.atec_4q01 = atec_4q01,
        this.atec_4q02 = atec_4q02,
        this.atec_4q03 = atec_4q03,
        this.atec_4q04 = atec_4q04,
        this.atec_4q05 = atec_4q05,
        this.atec_4q06 = atec_4q06,
        this.atec_4q07 = atec_4q07,
        this.atec_4q08 = atec_4q08,
        this.atec_4q09 = atec_4q09,
        this.atec_4q10 = atec_4q10,
        this.atec_4q11 = atec_4q11,
        this.atec_4q12 = atec_4q12,
        this.atec_4q13 = atec_4q13,
        this.atec_4q14 = atec_4q14,
        this.atec_4q15 = atec_4q15,
        this.atec_4q16 = atec_4q16,
        this.atec_4q17 = atec_4q17,
        this.atec_4q18 = atec_4q18,
        this.atec_4q19 = atec_4q19,
        this.atec_4q20 = atec_4q20,
        this.atec_4q21 = atec_4q21,
        this.atec_4q22 = atec_4q22,
        this.atec_4q23 = atec_4q23,
        this.atec_4q24 = atec_4q24,
        this.atec_4q25 = atec_4q25,
        //Atributos de controle
        this.atec_usuidcad = atec_usuidcad,
        this.atec_usuidedi = atec_usuidedi,
        this.atec_datacad = atec_datacad,
        this.atec_dataedi = atec_dataedi
                 
    }
}

AtecSchema.loadClass(Atec)
const AtecModel = mongoose.model('tb_atec', AtecSchema)
module.exports = {AtecModel,AtecSchema,
    atecEditar: async (req, res) => {
        //Pega data atual
        let dataAtual = new Date();
        //Pega o usuario atual
        let usuarioAtual = req.cookies['idUsu'];
        let resultado;
        
        //Realiza Atualização
        await AtecModel.findByIdAndUpdate(req.body.atecId, 
            {$set: {
                atec_beneid : req.body.atecBeneid,
                atec_benesexo : req.body.atecBenesexo,
                atec_datecnasc : req.body.atecDatecnasc,
                atec_idade : req.body.atecIdade,
                atec_preenchido : req.body.atecPreenchido,
                atec_paren : req.body.atecParen,
                atec_teraacompid : req.body.atecTeraacompid,
                atec_infoiniatec : req.body.atecInfoiniatec,
                atec_concluido : req.body.atecConcluido,
                atec_dataatec : req.body.atecDataatec,
                //Totais
                atec_atec1Total : req.body.atecAtec1Total,
                atec_atec2Total : req.body.atecAtec2Total,
                atec_atec3Total : req.body.atecAtec3Total,
                atec_atec4Total : req.body.atecAtec4Total,
                atec_totpont : req.body.atecTotpont,
                atec_comentatec : req.body.atecComentatec,
                //Questionário I - 1
                atec_1q01 : req.body.atec1Q01temp,
                atec_1q02 : req.body.atec1Q02temp,
                atec_1q03 : req.body.atec1Q03temp,
                atec_1q04 : req.body.atec1Q04temp,
                atec_1q05 : req.body.atec1Q05temp,
                atec_1q06 : req.body.atec1Q06temp,
                atec_1q07 : req.body.atec1Q07temp,
                atec_1q08 : req.body.atec1Q08temp,
                atec_1q09 : req.body.atec1Q09temp,
                atec_1q10 : req.body.atec1Q10temp,
                atec_1q11 : req.body.atec1Q11temp,
                atec_1q12 : req.body.atec1Q12temp,
                atec_1q13 : req.body.atec1Q13temp,
                atec_1q14 : req.body.atec1Q14temp,
                // Questionário II - 2 
                atec_2q01 : req.body.atec2Q01temp,
                atec_2q02 : req.body.atec2Q02temp,
                atec_2q03 : req.body.atec2Q03temp,
                atec_2q04 : req.body.atec2Q04temp,
                atec_2q05 : req.body.atec2Q05temp,
                atec_2q06 : req.body.atec2Q06temp,
                atec_2q07 : req.body.atec2Q07temp,
                atec_2q08 : req.body.atec2Q08temp,
                atec_2q09 : req.body.atec2Q09temp,
                atec_2q10 : req.body.atec2Q10temp,
                atec_2q11 : req.body.atec2Q11temp,
                atec_2q12 : req.body.atec2Q12temp,
                atec_2q13 : req.body.atec2Q13temp,
                atec_2q14 : req.body.atec2Q14temp,
                atec_2q15 : req.body.atec2Q15temp,
                atec_2q16 : req.body.atec2Q16temp,
                atec_2q17 : req.body.atec2Q17temp,
                atec_2q18 : req.body.atec2Q18temp,
                atec_2q19 : req.body.atec2Q19temp,
                atec_2q20 : req.body.atec2Q20temp,
                // Questionário III - 3 
                atec_3q01 : req.body.atec3Q01temp,
                atec_3q02 : req.body.atec3Q02temp,
                atec_3q03 : req.body.atec3Q03temp,
                atec_3q04 : req.body.atec3Q04temp,
                atec_3q05 : req.body.atec3Q05temp,
                atec_3q06 : req.body.atec3Q06temp,
                atec_3q07 : req.body.atec3Q07temp,
                atec_3q08 : req.body.atec3Q08temp,
                atec_3q09 : req.body.atec3Q09temp,
                atec_3q10 : req.body.atec3Q10temp,
                atec_3q11 : req.body.atec3Q11temp,
                atec_3q12 : req.body.atec3Q12temp,
                atec_3q13 : req.body.atec3Q13temp,
                atec_3q14 : req.body.atec3Q14temp,
                atec_3q15 : req.body.atec3Q15temp,
                atec_3q16 : req.body.atec3Q16temp,
                atec_3q17 : req.body.atec3Q17temp,
                atec_3q18 : req.body.atec3Q18temp,
                // Questionário IV
                atec_4q01 : req.body.atec4Q01temp,
                atec_4q02 : req.body.atec4Q02temp,
                atec_4q03 : req.body.atec4Q03temp,
                atec_4q04 : req.body.atec4Q04temp,
                atec_4q05 : req.body.atec4Q05temp,
                atec_4q06 : req.body.atec4Q06temp,
                atec_4q07 : req.body.atec4Q07temp,
                atec_4q08 : req.body.atec4Q08temp,
                atec_4q09 : req.body.atec4Q09temp,
                atec_4q10 : req.body.atec4Q10temp,
                atec_4q11 : req.body.atec4Q11temp,
                atec_4q12 : req.body.atec4Q12temp,
                atec_4q13 : req.body.atec4Q13temp,
                atec_4q14 : req.body.atec4Q14temp,
                atec_4q15 : req.body.atec4Q15temp,
                atec_4q16 : req.body.atec4Q16temp,
                atec_4q17 : req.body.atec4Q17temp,
                atec_4q18 : req.body.atec4Q18temp,
                atec_4q19 : req.body.atec4Q19temp,
                atec_4q20 : req.body.atec4Q20temp,
                atec_4q21 : req.body.atec4Q21temp,
                atec_4q22 : req.body.atec4Q22temp,
                atec_4q23 : req.body.atec4Q23temp,
                atec_4q24 : req.body.atec4Q24temp,
                atec_4q25 : req.body.atec4Q25temp,
                //Atributos de controle
                atec_usuidedi : usuarioAtual,
                atec_dataedi : dataAtual.toISOString()
                }}
        ).then((res) =>{
            console.log("Salvo")
            resultado = true;
        }).catch((err) =>{
            console.log("erro mongo:")
            console.log(err)
            resultado = err;
        })
        return resultado;
    },
    atecAdicionar: async (req,res) => {
        //Pega data atual
        let dataAtual = new Date();
        //Pega o usuario atual
        let usuarioAtual = req.cookies['idUsu'];

        const newAtec = new AtecModel({
            atec_beneid : req.body.atecBeneid,
            atec_benesexo : req.body.atecBenesexo,
            atec_datecnasc : req.body.atecDatecnasc,
            atec_idade : req.body.atecIdade,
            atec_preenchido : req.body.atecPreenchido,
            atec_paren : req.body.atecParen,
            atec_teraacompid : req.body.atecTeraacompid,
            atec_infoiniatec : req.body.atecInfoiniatec,
            atec_concluido : req.body.atecConcluido,
            atec_dataatec : req.body.atecDataatec,
            //Totais
            atec_atec1Total : req.body.atecAtec1Total,
            atec_atec2Total : req.body.atecAtec2Total,
            atec_atec3Total : req.body.atecAtec3Total,
            atec_atec4Total : req.body.atecAtec4Total,
            atec_totpont : req.body.atecTotpont,
            atec_comentatec : req.body.atecComentatec,
            //Questionário I - 1
            atec_1q01 : req.body.atec1Q01,
            atec_1q02 : req.body.atec1Q02,
            atec_1q03 : req.body.atec1Q03,
            atec_1q04 : req.body.atec1Q04,
            atec_1q05 : req.body.atec1Q05,
            atec_1q06 : req.body.atec1Q06,
            atec_1q07 : req.body.atec1Q07,
            atec_1q08 : req.body.atec1Q08,
            atec_1q09 : req.body.atec1Q09,
            atec_1q10 : req.body.atec1Q10,
            atec_1q11 : req.body.atec1Q11,
            atec_1q12 : req.body.atec1Q12,
            atec_1q13 : req.body.atec1Q13,
            atec_1q14 : req.body.atec1Q14,
            // Questionário II - 2 
            atec_2q01 : req.body.atec2Q01,
            atec_2q02 : req.body.atec2Q02,
            atec_2q03 : req.body.atec2Q03,
            atec_2q04 : req.body.atec2Q04,
            atec_2q05 : req.body.atec2Q05,
            atec_2q06 : req.body.atec2Q06,
            atec_2q07 : req.body.atec2Q07,
            atec_2q08 : req.body.atec2Q08,
            atec_2q09 : req.body.atec2Q09,
            atec_2q10 : req.body.atec2Q10,
            atec_2q11 : req.body.atec2Q11,
            atec_2q12 : req.body.atec2Q12,
            atec_2q13 : req.body.atec2Q13,
            atec_2q14 : req.body.atec2Q14,
            atec_2q15 : req.body.atec2Q15,
            atec_2q16 : req.body.atec2Q16,
            atec_2q17 : req.body.atec2Q17,
            atec_2q18 : req.body.atec2Q18,
            atec_2q19 : req.body.atec2Q19,
            atec_2q20 : req.body.atec2Q20,
            // Questionário III - 3 
            atec_3q01 : req.body.atec3Q01,
            atec_3q02 : req.body.atec3Q02,
            atec_3q03 : req.body.atec3Q03,
            atec_3q04 : req.body.atec3Q04,
            atec_3q05 : req.body.atec3Q05,
            atec_3q06 : req.body.atec3Q06,
            atec_3q07 : req.body.atec3Q07,
            atec_3q08 : req.body.atec3Q08,
            atec_3q09 : req.body.atec3Q09,
            atec_3q10 : req.body.atec3Q10,
            atec_3q11 : req.body.atec3Q11,
            atec_3q12 : req.body.atec3Q12,
            atec_3q13 : req.body.atec3Q13,
            atec_3q14 : req.body.atec3Q14,
            atec_3q15 : req.body.atec3Q15,
            atec_3q16 : req.body.atec3Q16,
            atec_3q17 : req.body.atec3Q17,
            atec_3q18 : req.body.atec3Q18,
            // Questionário IV
            atec_4q01 : req.body.atec4Q01,
            atec_4q02 : req.body.atec4Q02,
            atec_4q03 : req.body.atec4Q03,
            atec_4q04 : req.body.atec4Q04,
            atec_4q05 : req.body.atec4Q05,
            atec_4q06 : req.body.atec4Q06,
            atec_4q07 : req.body.atec4Q07,
            atec_4q08 : req.body.atec4Q08,
            atec_4q09 : req.body.atec4Q09,
            atec_4q10 : req.body.atec4Q10,
            atec_4q11 : req.body.atec4Q11,
            atec_4q12 : req.body.atec4Q12,
            atec_4q13 : req.body.atec4Q13,
            atec_4q14 : req.body.atec4Q14,
            atec_4q15 : req.body.atec4Q15,
            atec_4q16 : req.body.atec4Q16,
            atec_4q17 : req.body.atec4Q17,
            atec_4q18 : req.body.atec4Q18,
            atec_4q19 : req.body.atec4Q19,
            atec_4q20 : req.body.atec4Q20,
            atec_4q21 : req.body.atec4Q21,
            atec_4q22 : req.body.atec4Q22,
            atec_4q23 : req.body.atec4Q23,
            atec_4q24 : req.body.atec4Q24,
            atec_4q25 : req.body.atec4Q25,
            //Atributos de controle
            atec_usuidcad : usuarioAtual,
            atec_datacad : dataAtual.toISOString()
            
        });
        console.log("newAtec save");
        await newAtec.save().then(()=>{
            console.log("Cadastro realizado!");
            return true;
        }).catch((err) => {
            console.log(err)
            return err;
        });
    }
};