const { data } = require('jquery')
const mongoose = require('mongoose')
const ObjectId = mongoose.Types.ObjectId

const BordoSchema = mongoose.Schema({
    bordo_terapeutaid:{type: ObjectId, required: true},
    bordo_beneid:{type: ObjectId, required: true},
    bordo_escolaid:{type: ObjectId, required: true},
    bordo_dataativ :{type: Date, required: false},
    bordo_frequencia :{type: String, required: false},
    bordo_seguerotina :{type: String, required: false},
    bordo_seguerotinadesc :{type: String, required: false},
    bordo_estereotipas :{type: String, required: false},
    bordo_estereotipasdesc :{type: String, required: false},
    bordo_foco :{type: String, required: false},
    bordo_focodesc :{type: String, required: false},
    bordo_autocuidado :{type: String, required: false},
    bordo_autocuidadodesc :{type: String, required: false},
    bordo_aliindepende :{type: String, required: false},
    bordo_aliindependedesc :{type: String, required: false},
    bordo_escolalia :{type: String, required: false},
    bordo_escolaliadesc :{type: String, required: false},
    bordo_participa :{type: String, required: false},
    bordo_participadesc :{type: String, required: false},
    bordo_segue :{type: String, required: false},
    bordo_seguedesc :{type: String, required: false},
    bordo_repertorio :{type: String, required: false},
    bordo_repertoriodesc :{type: String, required: false},
    bordo_desorganiza :{type: String, required: false},
    bordo_desorganizadesc :{type: String, required: false},
    bordo_autoagressao :{type: String, required: false},
    bordo_autoagressaodesc :{type: String, required: false},
    bordo_agrideadulto :{type: String, required: false},
    bordo_agrideadultodesc :{type: String, required: false},
    bordo_agridepares :{type: String, required: false},
    bordo_agrideparesdesc :{type: String, required: false},
    bordo_destruir :{type: String, required: false},
    bordo_destruirdesc :{type: String, required: false},
    bordo_gritos :{type: String, required: false},
    bordo_gritosdesc :{type: String, required: false},
    bordo_choros :{type: String, required: false},
    bordo_chorosdesc :{type: String, required: false},
    bordo_birras :{type: String, required: false},
    bordo_birrasdesc :{type: String, required: false},
    bordo_mandosadulto :{type: String, required: false},
    bordo_mandospares :{type: String, required: false},
    bordo_pergunta :{type: String, required: false},
    bordo_responde :{type: String, required: false},
    bordo_imita :{type: String, required: false},
    bordo_interacaoverbal :{type: String, required: false},
    bordo_verbaldesc :{type: String, required: false},
    bordo_colab :{type: String, required: false},
    bordo_colabdesc :{type: String, required: false},
    bordo_colabtodotempo :{type: String, required: false},
    bordo_colabtodotempodesc :{type: String, required: false},
    bordo_colabmaiortempo :{type: String, required: false},
    bordo_colabmaiortempodesc :{type: String, required: false},
    bordo_colabmetadetempo :{type: String, required: false},
    bordo_colabmetadetempodesc :{type: String, required: false},
    bordo_colabmenosmetadetempo :{type: String, required: false},
    bordo_colabmenosmetadetempodesc :{type: String, required: false},
    bordo_colabnao :{type: String, required: false},
    bordo_colabnaodesc :{type: String, required: false},
    bordo_ativsucedido :{type: String, required: false},
    bordo_ativnaosucedido :{type: String, required: false},
    bordo_adequadodificil :{type: String, required: false},
    bordo_adequadodifacil :{type: String, required: false},
    bordo_semativ :{type: String, required: false},
    bordo_mediacao :{type: String, required: false},
    bordo_adaptacao :{type: String, required: false},
    bordo_ativsaladesc :{type: String, required: false},
    bordo_brincousolonge :{type: String, required: false},
    bordo_brincousoperto :{type: String, required: false},
    bordo_tentoubrincar :{type: String, required: false},
    bordo_brincouparesindep :{type: String, required: false},
    bordo_brincouparesterapeuta :{type: String, required: false},
    bordo_naobrincar :{type: String, required: false},
    bordo_brincardesc :{type: String, required: false},
    bordo_lerso :{type: String, required: false},
    bordo_lerajuda :{type: String, required: false},
    bordo_fazsoma :{type: String, required: false},
    bordo_fazsomaqtnum :{type: String, required: false},
    bordo_subtrai :{type: String, required: false},
    bordo_subtraiqtnum :{type: String, required: false},
    bordo_dividir :{type: String, required: false},
    bordo_multiplicar :{type: String, required: false},
    bordo_escolardesc :{type: String, required: false},
    bordo_foranormal :{type: String, required: false},
    bordo_habilnova :{type: String, required: false},
    bordo_incidente :{type: String, required: false},
    bardo_aliindepende :{type: String, required: false},
    bardo_aliindependedesc :{type: String, required: false},
    bordo_obs :{type: String, required: false},
    bordo_selo :{type: String, required: false},
    bordo_datacad :{type: Date, required: false},
    bordo_dataedi :{type: String, required: false},
    bordo_usuidcad :{type: String, required: false},
    bordo_usuidedi :{type: String, required: false}



})

class Bordo{
    constructor(
        bordo_terapeutaid,
        bordo_beneid,
        bordo_escolaid,
        bordo_dataativ,
        bordo_frequencia,
        bordo_seguerotina,
        bordo_seguerotinadesc,
        bordo_estereotipas,
        bordo_estereotipasdesc,
        bordo_foco,
        bordo_focodesc,
        bordo_autocuidado,
        bordo_autocuidadodesc,
        bordo_aliindepende,
        bordo_aliindependedesc,
        bordo_escolalia,
        bordo_escolaliadesc,
        bordo_participa,
        bordo_participadesc,
        bordo_segue,
        bordo_seguedesc,
        bordo_repertorio,
        bordo_repertoriodesc,
        bordo_desorganiza,
        bordo_desorganizadesc,
        bordo_autoagressao,
        bordo_autoagressaodesc,
        bordo_agrideadulto,
        bordo_agrideadultodesc,
        bordo_agridepares,
        bordo_agrideparesdesc,
        bordo_destruir,
        bordo_destruirdesc,
        bordo_gritos,
        bordo_gritosdesc,
        bordo_choros,
        bordo_chorosdesc,
        bordo_birras,
        bordo_birrasdesc,
        bordo_mandosadulto,
        bordo_mandospares,
        bordo_pergunta,
        bordo_responde,
        bordo_imita,
        bordo_interacaoverbal,
        bordo_verbaldesc,
        bordo_colab,
        bordo_colabdesc,
        bordo_colabtodotempo,
        bordo_colabtodotempodesc,
        bordo_colabmaiortempo,
        bordo_colabmaiortempodesc,
        bordo_colabmetadetempo,
        bordo_colabmetadetempodesc,
        bordo_colabmenosmetadetempo,
        bordo_colabmenosmetadetempodesc,
        bordo_colabnao,
        bordo_colabnaodesc,
        bordo_ativsucedido,
        bordo_ativnaosucedido,
        bordo_adequadodificil,
        bordo_adequadodifacil,
        bordo_semativ,
        bordo_mediacao,
        bordo_adaptacao,
        bordo_ativsaladesc,
        bordo_brincousolonge,
        bordo_brincousoperto,
        bordo_tentoubrincar,
        bordo_brincouparesindep,
        bordo_brincouparesterapeuta,
        bordo_naobrincar,
        bordo_brincardesc,
        bordo_lerso,
        bordo_lerajuda,
        bordo_fazsoma,
        bordo_fazsomaqtnum,
        bordo_subtrai,
        bordo_subtraiqtnum,
        bordo_dividir,
        bordo_multiplicar,
        bordo_escolardesc,
        bordo_foranormal,
        bordo_habilnova,
        bordo_incidente,
        bordo_obs,
        bordo_selo,
        bordo_datacad,
        bordo_dataedi,
        bordo_usuidcad,
        bordo_usuidedi

        
        ){
       
            this.bordo_terapeutaid = bordo_terapeutaid,
            this.bordo_beneid = bordo_beneid,
            this.bordo_escolaid = bordo_escolaid,
            this.bordo_dataativ = bordo_dataativ,
            this.bordo_frequencia = bordo_frequencia,
            this.bordo_seguerotina = bordo_seguerotina,
            this.bordo_seguerotinadesc = bordo_seguerotinadesc,
            this.bordo_estereotipas = bordo_estereotipas,
            this.bordo_estereotipasdesc = bordo_estereotipasdesc,
            this.bordo_foco = bordo_foco,
            this.bordo_focodesc = bordo_focodesc,
            this.bordo_autocuidado = bordo_autocuidado,
            this.bordo_autocuidadodesc = bordo_autocuidadodesc,
            this.bordo_aliindepende = bordo_aliindepende,
            this.bordo_aliindependedesc = bordo_aliindependedesc,
            this.bordo_escolalia = bordo_escolalia,
            this.bordo_escolaliadesc = bordo_escolaliadesc,
            this.bordo_participa = bordo_participa,
            this.bordo_participadesc = bordo_participadesc,
            this.bordo_segue = bordo_segue,
            this.bordo_seguedesc = bordo_seguedesc,
            this.bordo_repertorio = bordo_repertorio,
            this.bordo_repertoriodesc = bordo_repertoriodesc,
            this.bordo_desorganiza = bordo_desorganiza,
            this.bordo_desorganizadesc = bordo_desorganizadesc,
            this.bordo_autoagressao = bordo_autoagressao,
            this.bordo_autoagressaodesc = bordo_autoagressaodesc,
            this.bordo_agrideadulto = bordo_agrideadulto,
            this.bordo_agrideadultodesc = bordo_agrideadultodesc,
            this.bordo_agridepares = bordo_agridepares,
            this.bordo_agrideparesdesc = bordo_agrideparesdesc,
            this.bordo_destruir = bordo_destruir,
            this.bordo_destruirdesc = bordo_destruirdesc,
            this.bordo_gritos = bordo_gritos,
            this.bordo_gritosdesc = bordo_gritosdesc,
            this.bordo_choros = bordo_choros,
            this.bordo_chorosdesc = bordo_chorosdesc,
            this.bordo_birras = bordo_birras,
            this.bordo_birrasdesc = bordo_birrasdesc,
            this.bordo_mandosadulto = bordo_mandosadulto,
            this.bordo_mandospares = bordo_mandospares,
            this.bordo_pergunta = bordo_pergunta,
            this.bordo_responde = bordo_responde,
            this.bordo_imita = bordo_imita,
            this.bordo_interacaoverbal = bordo_interacaoverbal,
            this.bordo_verbaldesc = bordo_verbaldesc,
            this.bordo_colab = bordo_colab,
            this.bordo_colabdesc = bordo_colabdesc,
            this.bordo_colabtodotempo = bordo_colabtodotempo,
            this.bordo_colabtodotempodesc = bordo_colabtodotempodesc,
            this.bordo_colabmaiortempo = bordo_colabmaiortempo,
            this.bordo_colabmaiortempodesc = bordo_colabmaiortempodesc,
            this.bordo_colabmetadetempo = bordo_colabmetadetempo,
            this.bordo_colabmetadetempodesc = bordo_colabmetadetempodesc,
            this.bordo_colabmenosmetadetempo = bordo_colabmenosmetadetempo,
            this.bordo_colabmenosmetadetempodesc = bordo_colabmenosmetadetempodesc,
            this.bordo_colabnao = bordo_colabnao,
            this.bordo_colabnaodesc = bordo_colabnaodesc,
            this.bordo_ativsucedido = bordo_ativsucedido,
            this.bordo_ativnaosucedido = bordo_ativnaosucedido,
            this.bordo_adequadodificil = bordo_adequadodificil,
            this.bordo_adequadodifacil = bordo_adequadodifacil,
            this.bordo_semativ = bordo_semativ,
            this.bordo_mediacao = bordo_mediacao,
            this.bordo_adaptacao = bordo_adaptacao,
            this.bordo_ativsaladesc = bordo_ativsaladesc,
            this.bordo_brincousolonge = bordo_brincousolonge,
            this.bordo_brincousoperto = bordo_brincousoperto,
            this.bordo_tentoubrincar = bordo_tentoubrincar,
            this.bordo_brincouparesindep = bordo_brincouparesindep,
            this.bordo_brincouparesterapeuta = bordo_brincouparesterapeuta,
            this.bordo_naobrincar = bordo_naobrincar,
            this.bordo_brincardesc = bordo_brincardesc,
            this.bordo_lerso = bordo_lerso,
            this.bordo_lerajuda = bordo_lerajuda,
            this.bordo_fazsoma = bordo_fazsoma,
            this.bordo_fazsomaqtnum = bordo_fazsomaqtnum,
            this.bordo_subtrai = bordo_subtrai,
            this.bordo_subtraiqtnum = bordo_subtraiqtnum,
            this.bordo_dividir = bordo_dividir,
            this.bordo_multiplicar = bordo_multiplicar,
            this.bordo_escolardesc = bordo_escolardesc,
            this.bordo_foranormal = bordo_foranormal,
            this.bordo_habilnova = bordo_habilnova,
            this.bordo_incidente = bordo_incidente,
            this.bordo_obs = bordo_obs,
            this.bordo_selo = bordo_selo,
            this.bordo_datacad = bordo_datacad,
            this.bordo_dataedi = bordo_dataedi,
            this.bordo_usuidcad = bordo_usuidcad,
            this.bordo_usuidedi = bordo_usuidedi
                
    }
}

BordoSchema.loadClass(Bordo)
const BordoModel = mongoose.model('tb_bordo', BordoSchema)
module.exports = {BordoModel,BordoSchema,
    bordoEditar: async (req, res) => {
        let dataAtual = new Date();
        let resultado;
        //Pega data atual
        
        //Realiza Atualização
        await BordoModel.findByIdAndUpdate(req.body.bordoId, 
            {$set: {
                bordo_terapeutaid: req.body.bordoTerapeutaid,
                bordo_beneid: req.body.bordoBeneid,
                bordo_escolaid: req.body.bordoEscolaid,
                bordo_frequencia: req.body.bordoFrequencia,
                bordo_dataativ : req.body.bordoDataativ,
                bordo_seguerotina: req.body.bordoSeguerotina,
                bordo_seguerotinadesc: req.body.bordoSeguerotinadesc,
                bordo_estereotipas: req.body.bordoEstereotipas,
                bordo_estereotipasdesc: req.body.bordoEstereotipasdesc,
                bordo_foco: req.body.bordoFoco,
                bordo_focodesc: req.body.bordoFocodesc,
                bordo_autocuidado: req.body.bordoAutocuidado,
                bordo_autocuidadodesc: req.body.bordoAutocuidadodesc,
                bordo_aliindepende: req.body.bordoAliindepende,
                bordo_aliindependedesc: req.body.bordoAliindependedesc,
                bordo_escolalia: req.body.bordoEscolalia,
                bordo_escolaliadesc: req.body.bordoEscolaliadesc,
                bordo_participa: req.body.bordoParticipa,
                bordo_participadesc: req.body.bordoParticipadesc,
                bordo_segue: req.body.bordoSegue,
                bordo_seguedesc: req.body.bordoSeguedesc,
                bordo_repertorio: req.body.bordoRepertorio,
                bordo_repertoriodesc: req.body.bordoRepertoriodesc,
                bordo_desorganiza: req.body.bordoDesorganiza,
                bordo_desorganizadesc: req.body.bordoDesorganizadesc,
                bordo_autoagressao: req.body.bordoAutoagressao,
                bordo_autoagressaodesc: req.body.bordoAutoagressaodesc,
                bordo_agrideadulto: req.body.bordoAgrideadulto,
                bordo_agrideadultodesc: req.body.bordoAgrideadultodesc,
                bordo_agridepares: req.body.bordoAgridepares,
                bordo_agrideparesdesc: req.body.bordoAgrideparesdesc,
                bordo_destruir: req.body.bordoDestruir,
                bordo_destruirdesc: req.body.bordoDestruirdesc,
                bordo_gritos: req.body.bordoGritos,
                bordo_gritosdesc: req.body.bordoGritosdesc,
                bordo_choros: req.body.bordoChoros,
                bordo_chorosdesc: req.body.bordoChorosdesc,
                bordo_birras: req.body.bordoBirras,
                bordo_birrasdesc: req.body.bordoBirrasdesc,
                bordo_mandosadulto: req.body.bordoMandosadulto,
                bordo_mandospares: req.body.bordoMandospares,
                bordo_pergunta: req.body.bordoPergunta,
                bordo_responde: req.body.bordoResponde,
                bordo_imita: req.body.bordoImita,
                bordo_interacaoverbal: req.body.bordoInteracaoverbal,
                bordo_verbaldesc: req.body.bordoVerbaldesc,
                bordo_colab: req.body.bordoColab,
                bordo_colabdesc: req.body.bordoColabdesc,
                bordo_colabtodotempo: req.body.bordoColabtodotempo,
                bordo_colabtodotempodesc: req.body.bordoColabtodotempodesc,
                bordo_colabmaiortempo: req.body.bordoColabmaiortempo,
                bordo_colabmaiortempodesc: req.body.bordoColabmaiortempodesc,
                bordo_colabmetadetempo: req.body.bordoColabmetadetempo,
                bordo_colabmetadetempodesc: req.body.bordoColabmetadetempodesc,
                bordo_colabmenosmetadetempo: req.body.bordoColabmenosmetadetempo,
                bordo_colabmenosmetadetempodesc: req.body.bordoColabmenosmetadetempodesc,
                bordo_colabnao: req.body.bordoColabnao,
                bordo_colabnaodesc: req.body.bordoColabnaodesc,
                bordo_ativsucedido: req.body.bordoAtivsucedido,
                bordo_ativnaosucedido: req.body.bordoAtivnaosucedido,
                bordo_adequadodificil: req.body.bordoAdequadodificil,
                bordo_adequadodifacil: req.body.bordoAdequadodifacil,
                bordo_semativ: req.body.bordoSemativ,
                bordo_mediacao: req.body.bordoMediacao,
                bordo_adaptacao: req.body.bordoAdaptacao,
                bordo_ativsaladesc: req.body.bordoAtivsaladesc,
                bordo_brincousolonge: req.body.bordoBrincousolonge,
                bordo_brincousoperto: req.body.bordoBrincousoperto,
                bordo_tentoubrincar: req.body.bordoTentoubrincar,
                bordo_brincouparesindep: req.body.bordoBrincouparesindep,
                bordo_brincouparesterapeuta: req.body.bordoBrincouparesterapeuta,
                bordo_naobrincar: req.body.bordoNaobrincar,
                bordo_brincardesc: req.body.bordoBrincardesc,
                bordo_lerso: req.body.bordoLerso,
                bordo_lerajuda: req.body.bordoLerajuda,
                bordo_fazsoma: req.body.bordoFazsoma,
                bordo_fazsomaqtnum: req.body.bordoFazsomaqtnum,
                bordo_subtrai: req.body.bordoSubtrai,
                bordo_subtraiqtnum: req.body.bordoSubtraiqtnum,
                bordo_dividir: req.body.bordoDividir,
                bordo_multiplicar: req.body.bordoMultiplicar,
                bordo_escolardesc: req.body.bordoEscolardesc,
                bordo_foranormal: req.body.bordoForanormal,
                bordo_habilnova: req.body.bordoHabilnova,
                bordo_incidente: req.body.bordoIncidente,
                bordo_obs: req.body.bordoObs,
                bordo_selo: req.body.bordoSelo,
                bordo_dataedi : req.body.bordoDataAtual.toISOString(),
                bordo_usuidedi: req.body.bordoUsuidedi

                
                
                }}
        ).then((res) =>{
            console.log("Salvo")
            resultado = true;
        }).catch((err) =>{
            console.log("erro mongo:")
            console.log(err)
            resultado = err;
        })
        return resultado;
    },
    bordoAdicionar: async (req,res) => {
        let dataAtual = new Date();
        console.log("bordomodel");
        console.log("req.body.bordoDatacad:")
        console.log(req.body.bordodata)
        const newBordo = new BordoModel({
            bordo_terapeutaid: req.body.bordoTerapeutaid,
            bordo_beneid: req.body.bordoBeneid,
            bordo_escolaid: req.body.bordoEscolaid,
            bordo_frequencia: req.body.bordoFrequencia,
            bordo_dataativ : req.body.bordoDataativ,
            bordo_seguerotina: req.body.bordoSeguerotina,
            bordo_seguerotinadesc: req.body.bordoSeguerotinadesc,
            bordo_estereotipas: req.body.bordoEstereotipas,
            bordo_estereotipasdesc: req.body.bordoEstereotipasdesc,
            bordo_foco: req.body.bordoFoco,
            bordo_focodesc: req.body.bordoFocodesc,
            bordo_autocuidado: req.body.bordoAutocuidado,
            bordo_autocuidadodesc: req.body.bordoAutocuidadodesc,
            bordo_aliindepende: req.body.bordoAliindepende,
            bordo_aliindependedesc: req.body.bordoAliindependedesc,
            bordo_escolalia: req.body.bordoEscolalia,
            bordo_escolaliadesc: req.body.bordoEscolaliadesc,
            bordo_participa: req.body.bordoParticipa,
            bordo_participadesc: req.body.bordoParticipadesc,
            bordo_segue: req.body.bordoSegue,
            bordo_seguedesc: req.body.bordoSeguedesc,
            bordo_repertorio: req.body.bordoRepertorio,
            bordo_repertoriodesc: req.body.bordoRepertoriodesc,
            bordo_desorganiza: req.body.bordoDesorganiza,
            bordo_desorganizadesc: req.body.bordoDesorganizadesc,
            bordo_autoagressao: req.body.bordoAutoagressao,
            bordo_autoagressaodesc: req.body.bordoAutoagressaodesc,
            bordo_agrideadulto: req.body.bordoAgrideadulto,
            bordo_agrideadultodesc: req.body.bordoAgrideadultodesc,
            bordo_agridepares: req.body.bordoAgridepares,
            bordo_agrideparesdesc: req.body.bordoAgrideparesdesc,
            bordo_destruir: req.body.bordoDestruir,
            bordo_destruirdesc: req.body.bordoDestruirdesc,
            bordo_gritos: req.body.bordoGritos,
            bordo_gritosdesc: req.body.bordoGritosdesc,
            bordo_choros: req.body.bordoChoros,
            bordo_chorosdesc: req.body.bordoChorosdesc,
            bordo_birras: req.body.bordoBirras,
            bordo_birrasdesc: req.body.bordoBirrasdesc,
            bordo_mandosadulto: req.body.bordoMandosadulto,
            bordo_mandospares: req.body.bordoMandospares,
            bordo_pergunta: req.body.bordoPergunta,
            bordo_responde: req.body.bordoResponde,
            bordo_imita: req.body.bordoImita,
            bordo_interacaoverbal: req.body.bordoInteracaoverbal,
            bordo_verbaldesc: req.body.bordoVerbaldesc,
            bordo_colab: req.body.bordoColab,
            bordo_colabdesc: req.body.bordoColabdesc,
            bordo_colabtodotempo: req.body.bordoColabtodotempo,
            bordo_colabtodotempodesc: req.body.bordoColabtodotempodesc,
            bordo_colabmaiortempo: req.body.bordoColabmaiortempo,
            bordo_colabmaiortempodesc: req.body.bordoColabmaiortempodesc,
            bordo_colabmetadetempo: req.body.bordoColabmetadetempo,
            bordo_colabmetadetempodesc: req.body.bordoColabmetadetempodesc,
            bordo_colabmenosmetadetempo: req.body.bordoColabmenosmetadetempo,
            bordo_colabmenosmetadetempodesc: req.body.bordoColabmenosmetadetempodesc,
            bordo_colabnao: req.body.bordoColabnao,
            bordo_colabnaodesc: req.body.bordoColabnaodesc,
            bordo_ativsucedido: req.body.bordoAtivsucedido,
            bordo_ativnaosucedido: req.body.bordoAtivnaosucedido,
            bordo_adequadodificil: req.body.bordoAdequadodificil,
            bordo_adequadodifacil: req.body.bordoAdequadodifacil,
            bordo_semativ: req.body.bordoSemativ,
            bordo_mediacao: req.body.bordoMediacao,
            bordo_adaptacao: req.body.bordoAdaptacao,
            bordo_ativsaladesc: req.body.bordoAtivsaladesc,
            bordo_brincousolonge: req.body.bordoBrincousolonge,
            bordo_brincousoperto: req.body.bordoBrincousoperto,
            bordo_tentoubrincar: req.body.bordoTentoubrincar,
            bordo_brincouparesindep: req.body.bordoBrincouparesindep,
            bordo_brincouparesterapeuta: req.body.bordoBrincouparesterapeuta,
            bordo_naobrincar: req.body.bordoNaobrincar,
            bordo_brincardesc: req.body.bordoBrincardesc,
            bordo_lerso: req.body.bordoLerso,
            bordo_lerso: req.body.bardoAliindepende,
            bordo_lerajuda: req.body.bordoLerajuda,
            bordo_fazsoma: req.body.bordoFazsoma,
            bordo_fazsomaqtnum: req.body.bordoFazsomaqtnum,
            bordo_subtrai: req.body.bordoSubtrai,
            bordo_subtraiqtnum: req.body.bordoSubtraiqtnum,
            bordo_dividir: req.body.bordoDividir,
            bordo_multiplicar: req.body.bordoMultiplicar,
            bordo_escolardesc: req.body.bordoEscolardesc,
            bordo_foranormal: req.body.bordoForanormal,
            bordo_habilnova: req.body.bordoHabilnova,
            bordo_incidente: req.body.bordoIncidente,
            bordo_obs: req.body.bordoObs,
            bordo_selo: req.body.bordoSelo,
            bordo_datacad: dataAtual,
            bordo_usuidcad: req.body.bordoUsuidedi
            
        });
        console.log("newBordo save");
        await newBordo.save().then(()=>{
            console.log("Cadastro realizado!");
            return true;
        }).catch((err) => {
            console.log(err)
            return err;
        });
    }
};