const mongoose = require('mongoose')
const ObjectId = mongoose.Types.ObjectId

const FolregSchema = mongoose.Schema({
    folreg_tiporeg :{ type: String, required: false },
    folreg_datareg :{ type: String, required: false },
    folreg_beneid :{ type: ObjectId, required: false },
    folreg_progid :{ type: ObjectId, required: false },
    folreg_progtipoid :{ type: ObjectId, required: false },
    folreg_prognivelid :{ type: ObjectId, required: false },
    folreg_setid :{ type: ObjectId, required: false },
    folreg_usuid :{ type: ObjectId, required: false },
    folreg_qtest :{ type: String, required: false },
    folreg_esta :{ type: String, required: false },
    folreg_estb :{ type: String, required: false },
    folreg_estc :{ type: String, required: false },
    folreg_estd :{ type: String, required: false },
    folreg_este :{ type: String, required: false },
    folreg_estf :{ type: String, required: false },
    folreg_estg :{ type: String, required: false },
    folreg_esth :{ type: String, required: false },
    folreg_esti :{ type: String, required: false },
    folreg_estj :{ type: String, required: false },
    folreg_estseq :{ type: String, required: false },
    folreg_obs :{ type: String, required: false },

    //Passos de Dicas
        //Simples
    folreg_passodicas :{ type: String, required: false },
        //Duplo Esquerda
    folreg_passodicae :{ type: String, required: false },
        //Duplo direita
    folreg_passodicad :{ type: String, required: false },

    //Tipos de Dicas herdadas do Programa ABA, ou seja,
    // ao escolher os tipos de dicas, eles são trazidos e carregados para os Registros Novos ou Editados e
    // o terapeuta escolhera algum ou todas as dicas a serem aplicadas
    //Simples
    folreg_tipodicaprogs :{ type: String, required: false },
        //Duplo Esquerda
    folreg_tipodicaproge :{ type: String, required: false },
        //Duplo direita
    folreg_tipodicaprogd :{ type: String, required: false },

    folreg_status :{ type: String, required: false },
    folreg_t1ests :{ type: String, required: false },
    folreg_t2ests :{ type: String, required: false },
    folreg_t3ests :{ type: String, required: false },
    folreg_t4ests :{ type: String, required: false },
    folreg_t5ests :{ type: String, required: false },
    folreg_t6ests :{ type: String, required: false },
    folreg_t7ests :{ type: String, required: false },
    folreg_t8ests :{ type: String, required: false },
    folreg_t9ests :{ type: String, required: false },
    folreg_t0ests :{ type: String, required: false },
    folreg_t1estd :{ type: String, required: false },
    folreg_t2estd :{ type: String, required: false },
    folreg_t3estd :{ type: String, required: false },
    folreg_t4estd :{ type: String, required: false },
    folreg_t5estd :{ type: String, required: false },
    folreg_t6estd :{ type: String, required: false },
    folreg_t7estd :{ type: String, required: false },
    folreg_t8estd :{ type: String, required: false },
    folreg_t9estd :{ type: String, required: false },
    folreg_t0estd :{ type: String, required: false },
    folreg_t1ressimples :{ type: String, required: false },
    folreg_t2ressimples :{ type: String, required: false },
    folreg_t3ressimples :{ type: String, required: false },
    folreg_t4ressimples :{ type: String, required: false },
    folreg_t5ressimples :{ type: String, required: false },
    folreg_t6ressimples :{ type: String, required: false },
    folreg_t7ressimples :{ type: String, required: false },
    folreg_t8ressimples :{ type: String, required: false },
    folreg_t9ressimples :{ type: String, required: false },
    folreg_t0ressimples :{ type: String, required: false },
    folreg_t1tipodsimples :{ type: String, required: false },
    folreg_t2tipodsimples :{ type: String, required: false },
    folreg_t3tipodsimples :{ type: String, required: false },
    folreg_t4tipodsimples :{ type: String, required: false },
    folreg_t5tipodsimples :{ type: String, required: false },
    folreg_t6tipodsimples :{ type: String, required: false },
    folreg_t7tipodsimples :{ type: String, required: false },
    folreg_t8tipodsimples :{ type: String, required: false },
    folreg_t9tipodsimples :{ type: String, required: false },
    folreg_t0tipodsimples :{ type: String, required: false },
    folreg_t1resesqu :{ type: String, required: false },
    folreg_t2resesqu :{ type: String, required: false },
    folreg_t3resesqu :{ type: String, required: false },
    folreg_t4resesqu :{ type: String, required: false },
    folreg_t5resesqu :{ type: String, required: false },
    folreg_t6resesqu :{ type: String, required: false },
    folreg_t7resesqu :{ type: String, required: false },
    folreg_t8resesqu :{ type: String, required: false },
    folreg_t9resesqu :{ type: String, required: false },
    folreg_t0resesqu :{ type: String, required: false },
    folreg_t1resdir :{ type: String, required: false },
    folreg_t2resdir :{ type: String, required: false },
    folreg_t3resdir :{ type: String, required: false },
    folreg_t4resdir :{ type: String, required: false },
    folreg_t5resdir :{ type: String, required: false },
    folreg_t6resdir :{ type: String, required: false },
    folreg_t7resdir :{ type: String, required: false },
    folreg_t8resdir :{ type: String, required: false },
    folreg_t9resdir :{ type: String, required: false },
    folreg_t0resdir :{ type: String, required: false },
    folreg_t1tipodesqu :{ type: String, required: false },
    folreg_t2tipodesqu :{ type: String, required: false },
    folreg_t3tipodesqu :{ type: String, required: false },
    folreg_t4tipodesqu :{ type: String, required: false },
    folreg_t5tipodesqu :{ type: String, required: false },
    folreg_t6tipodesqu :{ type: String, required: false },
    folreg_t7tipodesqu :{ type: String, required: false },
    folreg_t8tipodesqu :{ type: String, required: false },
    folreg_t9tipodesqu :{ type: String, required: false },
    folreg_t0tipodesqu :{ type: String, required: false },
    folreg_t1tipodird :{ type: String, required: false },
    folreg_t2tipodird :{ type: String, required: false },
    folreg_t3tipodird :{ type: String, required: false },
    folreg_t4tipodird :{ type: String, required: false },
    folreg_t5tipodird :{ type: String, required: false },
    folreg_t6tipodird :{ type: String, required: false },
    folreg_t7tipodird :{ type: String, required: false },
    folreg_t8tipodird :{ type: String, required: false },
    folreg_t9tipodird :{ type: String, required: false },
    folreg_t0tipodird :{ type: String, required: false },
    folreg_totalsimples_i :{ type: String, required: false },
    folreg_totalsimples_e :{ type: String, required: false },
    folreg_totalsimples_plusd :{ type: String, required: false },
    folreg_totalsimples_minusd :{ type: String, required: false },
    folreg_totalduploesq_i :{ type: String, required: false },
    folreg_totalduploesq_e :{ type: String, required: false },
    folreg_totalduploesq_plusd :{ type: String, required: false },
    folreg_totalduploesq_minusd :{ type: String, required: false },
    folreg_totalduplodir_i :{ type: String, required: false },
    folreg_totalduplodir_e :{ type: String, required: false },
    folreg_totalduplodir_plusd :{ type: String, required: false },
    folreg_totalduplodir_minusd :{ type: String, required: false },
    //Atributos de controle
    folreg_usuidcad :{ type: ObjectId, required: false },
    folreg_usuidedi :{ type: ObjectId, required: false },
    folreg_datacad :{ type: String, required: false },
    folreg_dataedi :{ type: String, required: false },
    folreg_lixo :{ type: String, required: false }
    
})

class Folreg{
    constructor(
        folreg_tiporeg,
        folreg_datareg,
        folreg_beneid,
        folreg_progid,
        folreg_progtipoid,
        folreg_prognivelid,
        folreg_setid,
        folreg_usuid,
        folreg_qtest,
        folreg_esta,
        folreg_estb,
        folreg_estc,
        folreg_estd,
        folreg_este,
        folreg_estf,
        folreg_estg,
        folreg_esth,
        folreg_esti,
        folreg_estj,
        folreg_estseq,
        folreg_obs,

        //Passos de dicas
        folreg_passodicas,
        folreg_passodicae,
        folreg_passodicad,
        //Tipos de dicas originárias do Programa ABA
        folreg_tipodicaprogs,
        folreg_tipodicaproge,
        folreg_tipodicaprogd,

        folreg_status,
        folreg_t1ests,
        folreg_t2ests,
        folreg_t3ests,
        folreg_t4ests,
        folreg_t5ests,
        folreg_t6ests,
        folreg_t7ests,
        folreg_t8ests,
        folreg_t9ests,
        folreg_t0ests,
        folreg_t1estd,
        folreg_t2estd,
        folreg_t3estd,
        folreg_t4estd,
        folreg_t5estd,
        folreg_t6estd,
        folreg_t7estd,
        folreg_t8estd,
        folreg_t9estd,
        folreg_t0estd,
        folreg_t1ressimples,
        folreg_t2ressimples,
        folreg_t3ressimples,
        folreg_t4ressimples,
        folreg_t5ressimples,
        folreg_t6ressimples,
        folreg_t7ressimples,
        folreg_t8ressimples,
        folreg_t9ressimples,
        folreg_t0ressimples,
        folreg_t1tipodsimples,
        folreg_t2tipodsimples,
        folreg_t3tipodsimples,
        folreg_t4tipodsimples,
        folreg_t5tipodsimples,
        folreg_t6tipodsimples,
        folreg_t7tipodsimples,
        folreg_t8tipodsimples,
        folreg_t9tipodsimples,
        folreg_t0tipodsimples,
        folreg_t1resesqu,
        folreg_t2resesqu,
        folreg_t3resesqu,
        folreg_t4resesqu,
        folreg_t5resesqu,
        folreg_t6resesqu,
        folreg_t7resesqu,
        folreg_t8resesqu,
        folreg_t9resesqu,
        folreg_t0resesqu,
        folreg_t1resdir,
        folreg_t2resdir,
        folreg_t3resdir,
        folreg_t4resdir,
        folreg_t5resdir,
        folreg_t6resdir,
        folreg_t7resdir,
        folreg_t8resdir,
        folreg_t9resdir,
        folreg_t0resdir,
        folreg_t1tipodesqu,
        folreg_t2tipodesqu,
        folreg_t3tipodesqu,
        folreg_t4tipodesqu,
        folreg_t5tipodesqu,
        folreg_t6tipodesqu,
        folreg_t7tipodesqu,
        folreg_t8tipodesqu,
        folreg_t9tipodesqu,
        folreg_t0tipodesqu,
        folreg_t1tipodird,
        folreg_t2tipodird,
        folreg_t3tipodird,
        folreg_t4tipodird,
        folreg_t5tipodird,
        folreg_t6tipodird,
        folreg_t7tipodird,
        folreg_t8tipodird,
        folreg_t9tipodird,
        folreg_t0tipodird,
        folreg_totalsimples_i,
        folreg_totalsimples_e,
        folreg_totalsimples_plusd,
        folreg_totalsimples_minusd,
        folreg_totalduploesq_i,
        folreg_totalduploesq_e,
        folreg_totalduploesq_plusd,
        folreg_totalduploesq_minusd,
        folreg_totalduplodir_i,
        folreg_totalduplodir_e,
        folreg_totalduplodir_plusd,
        folreg_totalduplodir_minusd,
        //Atributos de controle
        folreg_usuidcad,
        folreg_usuidedi,
        folreg_datacad,
        folreg_dataedi,
        folreg_lixo
        
        ){
        
            this.folreg_tiporeg = folreg_tiporeg,
            this.folreg_datareg = folreg_datareg,
            this.folreg_beneid = folreg_beneid,
            this.folreg_progid = folreg_progid,
            this.folreg_progtipoid = folreg_progtipoid,
            this.folreg_prognivelid = folreg_prognivelid,
            this.folreg_setid = folreg_setid,
            this.folreg_usuid = folreg_usuid,
            this.folreg_qtest = folreg_qtest,
            this.folreg_esta = folreg_esta,
            this.folreg_estb = folreg_estb,
            this.folreg_estc = folreg_estc,
            this.folreg_estd = folreg_estd,
            this.folreg_este = folreg_este,
            this.folreg_estf = folreg_estf,
            this.folreg_estg = folreg_estg,
            this.folreg_esth = folreg_esth,
            this.folreg_esti = folreg_esti,
            this.folreg_estj = folreg_estj,
            this.folreg_estseq = folreg_estseq,
            this.folreg_obs = folreg_obs,

            //Passos de Dicas
            this.folreg_passodicas = folreg_passodicas,
            this.folreg_passodicae = folreg_passodicae,
            this.folreg_passodicad = folreg_passodicad,
             //Tipos de dicas originárias do Programa ABA
            this.folreg_tipodicaprogs = folreg_tipodicaprogs,
            this.folreg_tipodicaproge = folreg_tipodicaproge,
            this.folreg_tipodicaprogd = folreg_tipodicaprogd,

            this.folreg_status = folreg_status,
            this.folreg_t1ests = folreg_t1ests,
            this.folreg_t2ests = folreg_t2ests,
            this.folreg_t3ests = folreg_t3ests,
            this.folreg_t4ests = folreg_t4ests,
            this.folreg_t5ests = folreg_t5ests,
            this.folreg_t6ests = folreg_t6ests,
            this.folreg_t7ests = folreg_t7ests,
            this.folreg_t8ests = folreg_t8ests,
            this.folreg_t9ests = folreg_t9ests,
            this.folreg_t0ests = folreg_t0ests,
            this.folreg_t1estd = folreg_t1estd,
            this.folreg_t2estd = folreg_t2estd,
            this.folreg_t3estd = folreg_t3estd,
            this.folreg_t4estd = folreg_t4estd,
            this.folreg_t5estd = folreg_t5estd,
            this.folreg_t6estd = folreg_t6estd,
            this.folreg_t7estd = folreg_t7estd,
            this.folreg_t8estd = folreg_t8estd,
            this.folreg_t9estd = folreg_t9estd,
            this.folreg_t0estd = folreg_t0estd,
            this.folreg_t1ressimples = folreg_t1ressimples,
            this.folreg_t2ressimples = folreg_t2ressimples,
            this.folreg_t3ressimples = folreg_t3ressimples,
            this.folreg_t4ressimples = folreg_t4ressimples,
            this.folreg_t5ressimples = folreg_t5ressimples,
            this.folreg_t6ressimples = folreg_t6ressimples,
            this.folreg_t7ressimples = folreg_t7ressimples,
            this.folreg_t8ressimples = folreg_t8ressimples,
            this.folreg_t9ressimples = folreg_t9ressimples,
            this.folreg_t0ressimples = folreg_t0ressimples,
            this.folreg_t1tipodsimples = folreg_t1tipodsimples,
            this.folreg_t2tipodsimples = folreg_t2tipodsimples,
            this.folreg_t3tipodsimples = folreg_t3tipodsimples,
            this.folreg_t4tipodsimples = folreg_t4tipodsimples,
            this.folreg_t5tipodsimples = folreg_t5tipodsimples,
            this.folreg_t6tipodsimples = folreg_t6tipodsimples,
            this.folreg_t7tipodsimples = folreg_t7tipodsimples,
            this.folreg_t8tipodsimples = folreg_t8tipodsimples,
            this.folreg_t9tipodsimples = folreg_t9tipodsimples,
            this.folreg_t0tipodsimples = folreg_t0tipodsimples,
            this.folreg_t1resesqu = folreg_t1resesqu,
            this.folreg_t2resesqu = folreg_t2resesqu,
            this.folreg_t3resesqu = folreg_t3resesqu,
            this.folreg_t4resesqu = folreg_t4resesqu,
            this.folreg_t5resesqu = folreg_t5resesqu,
            this.folreg_t6resesqu = folreg_t6resesqu,
            this.folreg_t7resesqu = folreg_t7resesqu,
            this.folreg_t8resesqu = folreg_t8resesqu,
            this.folreg_t9resesqu = folreg_t9resesqu,
            this.folreg_t0resesqu = folreg_t0resesqu,
            this.folreg_t1resdir = folreg_t1resdir,
            this.folreg_t2resdir = folreg_t2resdir,
            this.folreg_t3resdir = folreg_t3resdir,
            this.folreg_t4resdir = folreg_t4resdir,
            this.folreg_t5resdir = folreg_t5resdir,
            this.folreg_t6resdir = folreg_t6resdir,
            this.folreg_t7resdir = folreg_t7resdir,
            this.folreg_t8resdir = folreg_t8resdir,
            this.folreg_t9resdir = folreg_t9resdir,
            this.folreg_t0resdir = folreg_t0resdir,
            this.folreg_t1tipodesqu = folreg_t1tipodesqu,
            this.folreg_t2tipodesqu = folreg_t2tipodesqu,
            this.folreg_t3tipodesqu = folreg_t3tipodesqu,
            this.folreg_t4tipodesqu = folreg_t4tipodesqu,
            this.folreg_t5tipodesqu = folreg_t5tipodesqu,
            this.folreg_t6tipodesqu = folreg_t6tipodesqu,
            this.folreg_t7tipodesqu = folreg_t7tipodesqu,
            this.folreg_t8tipodesqu = folreg_t8tipodesqu,
            this.folreg_t9tipodesqu = folreg_t9tipodesqu,
            this.folreg_t0tipodesqu = folreg_t0tipodesqu,
            this.folreg_t1tipodird = folreg_t1tipodird,
            this.folreg_t2tipodird = folreg_t2tipodird,
            this.folreg_t3tipodird = folreg_t3tipodird,
            this.folreg_t4tipodird = folreg_t4tipodird,
            this.folreg_t5tipodird = folreg_t5tipodird,
            this.folreg_t6tipodird = folreg_t6tipodird,
            this.folreg_t7tipodird = folreg_t7tipodird,
            this.folreg_t8tipodird = folreg_t8tipodird,
            this.folreg_t9tipodird = folreg_t9tipodird,
            this.folreg_t0tipodird = folreg_t0tipodird,
            this.folreg_totalsimples_i = folreg_totalsimples_i,
            this.folreg_totalsimples_e = folreg_totalsimples_e,
            this.folreg_totalsimples_plusd = folreg_totalsimples_plusd,
            this.folreg_totalsimples_minusd = folreg_totalsimples_minusd,
            this.folreg_totalduploesq_i = folreg_totalduploesq_i,
            this.folreg_totalduploesq_e = folreg_totalduploesq_e,
            this.folreg_totalduploesq_plusd = folreg_totalduploesq_plusd,
            this.folreg_totalduploesq_minusd = folreg_totalduploesq_minusd,
            this.folreg_totalduplodir_i = folreg_totalduplodir_i,
            this.folreg_totalduplodir_e = folreg_totalduplodir_e,
            this.folreg_totalduplodir_plusd = folreg_totalduplodir_plusd,
            this.folreg_totalduplodir_minusd = folreg_totalduplodir_minusd,
            //Atributos de controle
            this.folreg_usuidcad = folreg_usuidcad,
            this.folreg_usuidedi = folreg_usuidedi,
            this.folreg_datacad = folreg_datacad,
            this.folreg_dataedi = folreg_dataedi,
            this.folreg_lixo = folreg_lixo
            
    }
}

FolregSchema.loadClass(Folreg)
const FolregModel = mongoose.model('tb_folreg', FolregSchema)
module.exports = {FolregModel,FolregSchema,
    folregEditar: async (req, res) => {
       //Pega data atual
       let dataAtual = new Date();
       //Pega Usuário Atual
       let usuarioAtual = req.cookies['idUsu'];
       let resultado;
       //Realiza Atualização
        await FolregModel.findByIdAndUpdate(req.body.folregId, 
            {$set: {
                folreg_tiporeg : req.body.folregTiporeg,
                folreg_datareg : req.body.folregDatareg,
                folreg_beneid : req.body.folregBeneid,
                folreg_progid : req.body.folregProgid,
                folreg_progtipoid : req.body.folregProgtipoid,
                folreg_prognivelid : req.body.folregPrognivelid,
                folreg_setid : req.body.folregSetid,
                folreg_usuid : req.body.folregUsuid,
                folreg_qtest: req.body.folregQtest,
                folreg_esta : req.body.folregEsta,
                folreg_estb : req.body.folregEstb,
                folreg_estc : req.body.folregEstc,
                folreg_estd : req.body.folregEstd,
                folreg_este : req.body.folregEste,
                folreg_estf : req.body.folregEstf,
                folreg_estg : req.body.folregEstg,
                folreg_esth : req.body.folregEsth,
                folreg_esti : req.body.folregEsti,
                folreg_estj : req.body.folregEstj,
                folreg_estseq : req.body.folregEstseq,
                folreg_obs : req.body.folregObs,
                
                //Passos de Dicas
                folreg_passodicas : req.body.folregPassodicas,
                folreg_passodicae : req.body.folregPassodicae,
                folreg_passodicad : req.body.folregPassodicad,
                //Tipos de dicas originárias do Programa ABA
                folreg_tipodicaprogs : req.body.folregTipodicaprogs,
                folreg_tipodicaproge : req.body.folregTipodicaproge,
                folreg_tipodicaprogd : req.body.folregTipodicaprogd,

                folreg_status : req.body.folregStatus,
                folreg_t1ests : req.body.folregT1Ests,
                folreg_t2ests : req.body.folregT2Ests,
                folreg_t3ests : req.body.folregT3Ests,
                folreg_t4ests : req.body.folregT4Ests,
                folreg_t5ests : req.body.folregT5Ests,
                folreg_t6ests : req.body.folregT6Ests,
                folreg_t7ests : req.body.folregT7Ests,
                folreg_t8ests : req.body.folregT8Ests,
                folreg_t9ests : req.body.folregT9Ests,
                folreg_t0ests : req.body.folregT0Ests,
                folreg_t1estd : req.body.folregT1Estd,
                folreg_t2estd : req.body.folregT2Estd,
                folreg_t3estd : req.body.folregT3Estd,
                folreg_t4estd : req.body.folregT4Estd,
                folreg_t5estd : req.body.folregT5Estd,
                folreg_t6estd : req.body.folregT6Estd,
                folreg_t7estd : req.body.folregT7Estd,
                folreg_t8estd : req.body.folregT8Estd,
                folreg_t9estd : req.body.folregT9Estd,
                folreg_t0estd : req.body.folregT0Estd,
                folreg_t1ressimples : req.body.folregT1Ressimples,
                folreg_t2ressimples : req.body.folregT2Ressimples,
                folreg_t3ressimples : req.body.folregT3Ressimples,
                folreg_t4ressimples : req.body.folregT4Ressimples,
                folreg_t5ressimples : req.body.folregT5Ressimples,
                folreg_t6ressimples : req.body.folregT6Ressimples,
                folreg_t7ressimples : req.body.folregT7Ressimples,
                folreg_t8ressimples : req.body.folregT8Ressimples,
                folreg_t9ressimples : req.body.folregT9Ressimples,
                folreg_t0ressimples : req.body.folregT0Ressimples,
                folreg_t1tipodsimples : req.body.folregT1Tipodsimples,
                folreg_t2tipodsimples : req.body.folregT2Tipodsimples,
                folreg_t3tipodsimples : req.body.folregT3Tipodsimples,
                folreg_t4tipodsimples : req.body.folregT4Tipodsimples,
                folreg_t5tipodsimples : req.body.folregT5Tipodsimples,
                folreg_t6tipodsimples : req.body.folregT6Tipodsimples,
                folreg_t7tipodsimples : req.body.folregT7Tipodsimples,
                folreg_t8tipodsimples : req.body.folregT8Tipodsimples,
                folreg_t9tipodsimples : req.body.folregT9Tipodsimples,
                folreg_t0tipodsimples : req.body.folregT0Tipodsimples,
                folreg_t1resesqu : req.body.folregT1Resesqu,
                folreg_t2resesqu : req.body.folregT2Resesqu,
                folreg_t3resesqu : req.body.folregT3Resesqu,
                folreg_t4resesqu : req.body.folregT4Resesqu,
                folreg_t5resesqu : req.body.folregT5Resesqu,
                folreg_t6resesqu : req.body.folregT6Resesqu,
                folreg_t7resesqu : req.body.folregT7Resesqu,
                folreg_t8resesqu : req.body.folregT8Resesqu,
                folreg_t9resesqu : req.body.folregT9Resesqu,
                folreg_t0resesqu : req.body.folregT0Resesqu,
                folreg_t1resdir : req.body.folregT1Resdir,
                folreg_t2resdir : req.body.folregT2Resdir,
                folreg_t3resdir : req.body.folregT3Resdir,
                folreg_t4resdir : req.body.folregT4Resdir,
                folreg_t5resdir : req.body.folregT5Resdir,
                folreg_t6resdir : req.body.folregT6Resdir,
                folreg_t7resdir : req.body.folregT7Resdir,
                folreg_t8resdir : req.body.folregT8Resdir,
                folreg_t9resdir : req.body.folregT9Resdir,
                folreg_t0resdir : req.body.folregT0Resdir,
                folreg_t1tipodesqu : req.body.folregT1Tipodesqu,
                folreg_t2tipodesqu : req.body.folregT2Tipodesqu,
                folreg_t3tipodesqu : req.body.folregT3Tipodesqu,
                folreg_t4tipodesqu : req.body.folregT4Tipodesqu,
                folreg_t5tipodesqu : req.body.folregT5Tipodesqu,
                folreg_t6tipodesqu : req.body.folregT6Tipodesqu,
                folreg_t7tipodesqu : req.body.folregT7Tipodesqu,
                folreg_t8tipodesqu : req.body.folregT8Tipodesqu,
                folreg_t9tipodesqu : req.body.folregT9Tipodesqu,
                folreg_t0tipodesqu : req.body.folregT0Tipodesqu,
                folreg_t1tipodird : req.body.folregT1Tipodird,
                folreg_t2tipodird : req.body.folregT2Tipodird,
                folreg_t3tipodird : req.body.folregT3Tipodird,
                folreg_t4tipodird : req.body.folregT4Tipodird,
                folreg_t5tipodird : req.body.folregT5Tipodird,
                folreg_t6tipodird : req.body.folregT6Tipodird,
                folreg_t7tipodird : req.body.folregT7Tipodird,
                folreg_t8tipodird : req.body.folregT8Tipodird,
                folreg_t9tipodird : req.body.folregT9Tipodird,
                folreg_t0tipodird : req.body.folregT0Tipodird,
                folreg_totalsimples_i : req.body.folregTotalsimples_i,
                folreg_totalsimples_e : req.body.folregTotalsimples_e,
                folreg_totalsimples_plusd : req.body.folregTotalsimples_plusd,
                folreg_totalsimples_minusd : req.body.folregTotalsimples_minusd,
                folreg_totalduploesq_i : req.body.folregTotalduploesq_i,
                folreg_totalduploesq_e : req.body.folregTotalduploesq_e,
                folreg_totalduploesq_plusd : req.body.folregTotalduploesq_plusd,
                folreg_totalduploesq_minusd : req.body.folregTotalduploesq_minusd,
                folreg_totalduplodir_i : req.body.folregTotalduplodir_i,
                folreg_totalduplodir_e : req.body.folregTotalduplodir_e,
                folreg_totalduplodir_plusd : req.body.folregTotalduplodir_plusd,
                folreg_totalduplodir_minusd : req.body.folregTotalduplodir_minusd,
                //Atributos de controle
                folreg_usuidedi : usuarioAtual,
                folreg_dataedi : dataAtual.toISOString(),
                folreg_lixo : "false"

                
                }}
        ).then((res) =>{
            console.log("Salvo")
            resultado = true;
        }).catch((err) =>{
            console.log("erro mongo:")
            console.log(err)
            resultado = err;
        })
        return resultado;
    },
    folregAdicionar: async (req,res) => {
      //Pega data atual
      let dataAtual = new Date();
      //Pega Usuário Atual
      let usuarioAtual = req.cookies['idUsu'];
      let resultado;
      //Realiza Atualização
        const newFolreg = new FolregModel({
            folreg_tiporeg : req.body.folregTiporeg,
            folreg_datareg : req.body.folregDatareg,
            folreg_beneid : req.body.folregBeneid,
            folreg_progid : req.body.folregProgid,
            folreg_progtipoid : req.body.folregProgtipoid,
            folreg_prognivelid : req.body.folregPrognivelid,
            folreg_setid : req.body.folregSetid,
            folreg_usuid : req.body.folregUsuid,
            folreg_qtest: req.body.folregQtest,
            folreg_esta : req.body.folregEsta,
            folreg_estb : req.body.folregEstb,
            folreg_estc : req.body.folregEstc,
            folreg_estd : req.body.folregEstd,
            folreg_este : req.body.folregEste,
            folreg_estf : req.body.folregEstf,
            folreg_estg : req.body.folregEstg,
            folreg_esth : req.body.folregEsth,
            folreg_esti : req.body.folregEsti,
            folreg_estj : req.body.folregEstj,
            folreg_estseq : req.body.folregEstseq,
            folreg_obs : req.body.folregObs,
            
             //Passos de Dicas
             folreg_passodicas : req.body.folregPassodicas,
             folreg_passodicae : req.body.folregPassodicae,
             folreg_passodicad : req.body.folregPassodicad,
             //Tipos de dicas originárias do Programa ABA
             folreg_tipodicaprogs : req.body.folregTipodicaprogs,
             folreg_tipodicaproge : req.body.folregTipodicaproge,
             folreg_tipodicaprogd : req.body.folregTipodicaprogd,

            folreg_status : req.body.folregStatus,
            folreg_t1ests : req.body.folregT1Ests,
            folreg_t2ests : req.body.folregT2Ests,
            folreg_t3ests : req.body.folregT3Ests,
            folreg_t4ests : req.body.folregT4Ests,
            folreg_t5ests : req.body.folregT5Ests,
            folreg_t6ests : req.body.folregT6Ests,
            folreg_t7ests : req.body.folregT7Ests,
            folreg_t8ests : req.body.folregT8Ests,
            folreg_t9ests : req.body.folregT9Ests,
            folreg_t0ests : req.body.folregT0Ests,
            folreg_t1estd : req.body.folregT1Estd,
            folreg_t2estd : req.body.folregT2Estd,
            folreg_t3estd : req.body.folregT3Estd,
            folreg_t4estd : req.body.folregT4Estd,
            folreg_t5estd : req.body.folregT5Estd,
            folreg_t6estd : req.body.folregT6Estd,
            folreg_t7estd : req.body.folregT7Estd,
            folreg_t8estd : req.body.folregT8Estd,
            folreg_t9estd : req.body.folregT9Estd,
            folreg_t0estd : req.body.folregT0Estd,
            folreg_t1ressimples : req.body.folregT1Ressimples,
            folreg_t2ressimples : req.body.folregT2Ressimples,
            folreg_t3ressimples : req.body.folregT3Ressimples,
            folreg_t4ressimples : req.body.folregT4Ressimples,
            folreg_t5ressimples : req.body.folregT5Ressimples,
            folreg_t6ressimples : req.body.folregT6Ressimples,
            folreg_t7ressimples : req.body.folregT7Ressimples,
            folreg_t8ressimples : req.body.folregT8Ressimples,
            folreg_t9ressimples : req.body.folregT9Ressimples,
            folreg_t0ressimples : req.body.folregT0Ressimples,
            folreg_t1tipodsimples : req.body.folregT1Tipodsimples,
            folreg_t2tipodsimples : req.body.folregT2Tipodsimples,
            folreg_t3tipodsimples : req.body.folregT3Tipodsimples,
            folreg_t4tipodsimples : req.body.folregT4Tipodsimples,
            folreg_t5tipodsimples : req.body.folregT5Tipodsimples,
            folreg_t6tipodsimples : req.body.folregT6Tipodsimples,
            folreg_t7tipodsimples : req.body.folregT7Tipodsimples,
            folreg_t8tipodsimples : req.body.folregT8Tipodsimples,
            folreg_t9tipodsimples : req.body.folregT9Tipodsimples,
            folreg_t0tipodsimples : req.body.folregT0Tipodsimples,
            folreg_t1resesqu : req.body.folregT1Resesqu,
            folreg_t2resesqu : req.body.folregT2Resesqu,
            folreg_t3resesqu : req.body.folregT3Resesqu,
            folreg_t4resesqu : req.body.folregT4Resesqu,
            folreg_t5resesqu : req.body.folregT5Resesqu,
            folreg_t6resesqu : req.body.folregT6Resesqu,
            folreg_t7resesqu : req.body.folregT7Resesqu,
            folreg_t8resesqu : req.body.folregT8Resesqu,
            folreg_t9resesqu : req.body.folregT9Resesqu,
            folreg_t0resesqu : req.body.folregT0Resesqu,
            folreg_t1resdir : req.body.folregT1Resdir,
            folreg_t2resdir : req.body.folregT2Resdir,
            folreg_t3resdir : req.body.folregT3Resdir,
            folreg_t4resdir : req.body.folregT4Resdir,
            folreg_t5resdir : req.body.folregT5Resdir,
            folreg_t6resdir : req.body.folregT6Resdir,
            folreg_t7resdir : req.body.folregT7Resdir,
            folreg_t8resdir : req.body.folregT8Resdir,
            folreg_t9resdir : req.body.folregT9Resdir,
            folreg_t0resdir : req.body.folregT0Resdir,
            folreg_t1tipodesqu : req.body.folregT1Tipodesqu,
            folreg_t2tipodesqu : req.body.folregT2Tipodesqu,
            folreg_t3tipodesqu : req.body.folregT3Tipodesqu,
            folreg_t4tipodesqu : req.body.folregT4Tipodesqu,
            folreg_t5tipodesqu : req.body.folregT5Tipodesqu,
            folreg_t6tipodesqu : req.body.folregT6Tipodesqu,
            folreg_t7tipodesqu : req.body.folregT7Tipodesqu,
            folreg_t8tipodesqu : req.body.folregT8Tipodesqu,
            folreg_t9tipodesqu : req.body.folregT9Tipodesqu,
            folreg_t0tipodesqu : req.body.folregT0Tipodesqu,
            folreg_t1tipodird : req.body.folregT1Tipodird,
            folreg_t2tipodird : req.body.folregT2Tipodird,
            folreg_t3tipodird : req.body.folregT3Tipodird,
            folreg_t4tipodird : req.body.folregT4Tipodird,
            folreg_t5tipodird : req.body.folregT5Tipodird,
            folreg_t6tipodird : req.body.folregT6Tipodird,
            folreg_t7tipodird : req.body.folregT7Tipodird,
            folreg_t8tipodird : req.body.folregT8Tipodird,
            folreg_t9tipodird : req.body.folregT9Tipodird,
            folreg_t0tipodird : req.body.folregT0Tipodird,
            folreg_totalsimples_i : req.body.folregTotalsimples_i,
            folreg_totalsimples_e : req.body.folregTotalsimples_e,
            folreg_totalsimples_plusd : req.body.folregTotalsimples_plusd,
            folreg_totalsimples_minusd : req.body.folregTotalsimples_minusd,
            folreg_totalduploesq_i : req.body.folregTotalduploesq_i,
            folreg_totalduploesq_e : req.body.folregTotalduploesq_e,
            folreg_totalduploesq_plusd : req.body.folregTotalduploesq_plusd,
            folreg_totalduploesq_minusd : req.body.folregTotalduploesq_minusd,
            folreg_totalduplodir_i : req.body.folregTotalduplodir_i,
            folreg_totalduplodir_e : req.body.folregTotalduplodir_e,
            folreg_totalduplodir_plusd : req.body.folregTotalduplodir_plusd,
            folreg_totalduplodir_minusd : req.body.folregTotalduplodir_minusd,
            //Atributos de controle
            folreg_usuidcad : usuarioAtual,
            folreg_datacad : dataAtual.toISOString(),
            folreg_lixo : "false"

            
        });
        console.log("newAtend save");
        await newFolreg.save().then(()=>{
            console.log("Cadastro realizado!");
            return true;
        }).catch((err) => {
            console.log(err)
            return err;
        });
    }
};