const mongoose = require('mongoose')
const ObjectId = mongoose.Types.ObjectId

const SessaoSchema = mongoose.Schema({
    sessao_beneid :{ type: ObjectId, required: false },
    sessao_convid :{ type: ObjectId, required: false },
    sessao_terapiaid01 :{ type: ObjectId, required: false },
    sessao_qtterapiaprev01 :{ type: String, required: false },
    sessao_qtterapiacon01 :{ type: String, required: false },
    sessao_qtterapiasaldo01 :{ type: String, required: false },
    sessao_obssessao01 :{ type: String, required: false },
    sessao_terapiaid02 :{ type: ObjectId, required: false },
    sessao_qtterapiaprev02 :{ type: String, required: false },
    sessao_qtterapiacon02 :{ type: String, required: false },
    sessao_qtterapiasaldo02 :{ type: String, required: false },
    sessao_obssessao02 :{ type: String, required: false },
    sessao_terapiaid03 :{ type: ObjectId, required: false },
    sessao_qtterapiaprev03 :{ type: String, required: false },
    sessao_qtterapiacon03 :{ type: String, required: false },
    sessao_qtterapiasaldo03 :{ type: String, required: false },
    sessao_obssessao03 :{ type: String, required: false },
    sessao_terapiaid04 :{ type: ObjectId, required: false },
    sessao_qtterapiaprev04 :{ type: String, required: false },
    sessao_qtterapiacon04 :{ type: String, required: false },
    sessao_qtterapiasaldo04 :{ type: String, required: false },
    sessao_obssessao04 :{ type: String, required: false },
    sessao_terapiaid05 :{ type: ObjectId, required: false },
    sessao_qtterapiaprev05 :{ type: String, required: false },
    sessao_qtterapiacon05 :{ type: String, required: false },
    sessao_qtterapiasaldo05 :{ type: String, required: false },
    sessao_obssessao05 :{ type: String, required: false },
    sessao_terapiaid06 :{ type: ObjectId, required: false },
    sessao_qtterapiaprev06 :{ type: String, required: false },
    sessao_qtterapiacon06 :{ type: String, required: false },
    sessao_qtterapiasaldo06 :{ type: String, required: false },
    sessao_obssessao06 :{ type: String, required: false },
    sessao_terapiaid07 :{ type: ObjectId, required: false },
    sessao_qtterapiaprev07 :{ type: String, required: false },
    sessao_qtterapiacon07 :{ type: String, required: false },
    sessao_qtterapiasaldo07 :{ type: String, required: false },
    sessao_obssessao07 :{ type: String, required: false },
    sessao_terapiaid08 :{ type: ObjectId, required: false },
    sessao_qtterapiaprev08 :{ type: String, required: false },
    sessao_qtterapiacon08 :{ type: String, required: false },
    sessao_qtterapiasaldo08 :{ type: String, required: false },
    sessao_obssessao08 :{ type: String, required: false },
    sessao_terapiaid09 :{ type: ObjectId, required: false },
    sessao_qtterapiaprev09 :{ type: String, required: false },
    sessao_qtterapiacon09 :{ type: String, required: false },
    sessao_qtterapiasaldo09 :{ type: String, required: false },
    sessao_obssessao09 :{ type: String, required: false },
    sessao_terapiaid10 :{ type: ObjectId, required: false },
    sessao_qtterapiaprev10 :{ type: String, required: false },
    sessao_qtterapiacon10 :{ type: String, required: false },
    sessao_qtterapiasaldo10 :{ type: String, required: false },
    sessao_obssessao10 :{ type: String, required: false },
    sessao_terapiaid11 :{ type: ObjectId, required: false },
    sessao_qtterapiaprev11 :{ type: String, required: false },
    sessao_qtterapiacon11 :{ type: String, required: false },
    sessao_qtterapiasaldo11 :{ type: String, required: false },
    sessao_obssessao11 :{ type: String, required: false },
    sessao_terapiaid12 :{ type: ObjectId, required: false },
    sessao_qtterapiaprev12 :{ type: String, required: false },
    sessao_qtterapiacon12 :{ type: String, required: false },
    sessao_qtterapiasaldo12 :{ type: String, required: false },
    sessao_obssessao12 :{ type: String, required: false },
    sessao_terapiaid13 :{ type: ObjectId, required: false },
    sessao_qtterapiaprev13 :{ type: String, required: false },
    sessao_qtterapiacon13 :{ type: String, required: false },
    sessao_qtterapiasaldo13 :{ type: String, required: false },
    sessao_obssessao13 :{ type: String, required: false },
    sessao_terapiaid14 :{ type: ObjectId, required: false },
    sessao_qtterapiaprev14 :{ type: String, required: false },
    sessao_qtterapiacon14 :{ type: String, required: false },
    sessao_qtterapiasaldo14 :{ type: String, required: false },
    sessao_obssessao14 :{ type: String, required: false },
    sessao_terapiaid15 :{ type: ObjectId, required: false },
    sessao_qtterapiaprev15 :{ type: String, required: false },
    sessao_qtterapiacon15 :{ type: String, required: false },
    sessao_qtterapiasaldo15 :{ type: String, required: false },
    sessao_obssessao15 :{ type: String, required: false },
    sessao_terapiaid16 :{ type: ObjectId, required: false },
    sessao_qtterapiaprev16 :{ type: String, required: false },
    sessao_qtterapiacon16 :{ type: String, required: false },
    sessao_qtterapiasaldo16 :{ type: String, required: false },
    sessao_obssessao16 :{ type: String, required: false },
    sessao_terapiaid17 :{ type: ObjectId, required: false },
    sessao_qtterapiaprev17 :{ type: String, required: false },
    sessao_qtterapiacon17 :{ type: String, required: false },
    sessao_qtterapiasaldo17 :{ type: String, required: false },
    sessao_obssessao17 :{ type: String, required: false },
    sessao_terapiaid18 :{ type: ObjectId, required: false },
    sessao_qtterapiaprev18 :{ type: String, required: false },
    sessao_qtterapiacon18 :{ type: String, required: false },
    sessao_qtterapiasaldo18 :{ type: String, required: false },
    sessao_obssessao18 :{ type: String, required: false },
    sessao_terapiaid19 :{ type: ObjectId, required: false },
    sessao_qtterapiaprev19 :{ type: String, required: false },
    sessao_qtterapiacon19 :{ type: String, required: false },
    sessao_qtterapiasaldo19 :{ type: String, required: false },
    sessao_obssessao19 :{ type: String, required: false },
    sessao_terapiaid20 :{ type: ObjectId, required: false },
    sessao_qtterapiaprev20 :{ type: String, required: false },
    sessao_qtterapiacon20 :{ type: String, required: false },
    sessao_qtterapiasaldo20 :{ type: String, required: false },
    sessao_obssessao20 :{ type: String, required: false },
    sessao_terapiaid21 :{ type: ObjectId, required: false },
    sessao_qtterapiaprev21 :{ type: String, required: false },
    sessao_qtterapiacon21 :{ type: String, required: false },
    sessao_qtterapiasaldo21 :{ type: String, required: false },
    sessao_obssessao21 :{ type: String, required: false },
    sessao_terapiaid22 :{ type: ObjectId, required: false },
    sessao_qtterapiaprev22 :{ type: String, required: false },
    sessao_qtterapiacon22 :{ type: String, required: false },
    sessao_qtterapiasaldo22 :{ type: String, required: false },
    sessao_obssessao22 :{ type: String, required: false },
    sessao_terapiaid23 :{ type: ObjectId, required: false },
    sessao_qtterapiaprev23 :{ type: String, required: false },
    sessao_qtterapiacon23 :{ type: String, required: false },
    sessao_qtterapiasaldo23 :{ type: String, required: false },
    sessao_obssessao23 :{ type: String, required: false },
    sessao_terapiaid24 :{ type: ObjectId, required: false },
    sessao_qtterapiaprev24 :{ type: String, required: false },
    sessao_qtterapiacon24 :{ type: String, required: false },
    sessao_qtterapiasaldo24 :{ type: String, required: false },
    sessao_obssessao24 :{ type: String, required: false },
    sessao_terapiaid25 :{ type: ObjectId, required: false },
    sessao_qtterapiaprev25 :{ type: String, required: false },
    sessao_qtterapiacon25 :{ type: String, required: false },
    sessao_qtterapiasaldo25 :{ type: String, required: false },
    sessao_obssessao25 :{ type: String, required: false },
    //Atributos de controle
    sessao_usuidcad :{ type: ObjectId, required: false },
    sessao_usuidedi :{ type: ObjectId, required: false },
    sessao_datacad :{ type: String, required: false },
    sessao_dataedi :{ type: String, required: false }




    
})

class Sessao{
    constructor(
        sessao_beneid,
        sessao_convid,
        sessao_terapiaid01,
        sessao_qtterapiaprev01,
        sessao_qtterapiacon01,
        sessao_qtterapiasaldo01,
        sessao_obssessao01,
        sessao_terapiaid02,
        sessao_qtterapiaprev02,
        sessao_qtterapiacon02,
        sessao_qtterapiasaldo02,
        sessao_obssessao02,
        sessao_terapiaid03,
        sessao_qtterapiaprev03,
        sessao_qtterapiacon03,
        sessao_qtterapiasaldo03,
        sessao_obssessao03,
        sessao_terapiaid04,
        sessao_qtterapiaprev04,
        sessao_qtterapiacon04,
        sessao_qtterapiasaldo04,
        sessao_obssessao04,
        sessao_terapiaid05,
        sessao_qtterapiaprev05,
        sessao_qtterapiacon05,
        sessao_qtterapiasaldo05,
        sessao_obssessao05,
        sessao_terapiaid06,
        sessao_qtterapiaprev06,
        sessao_qtterapiacon06,
        sessao_qtterapiasaldo06,
        sessao_obssessao06,
        sessao_terapiaid07,
        sessao_qtterapiaprev07,
        sessao_qtterapiacon07,
        sessao_qtterapiasaldo07,
        sessao_obssessao07,
        sessao_terapiaid08,
        sessao_qtterapiaprev08,
        sessao_qtterapiacon08,
        sessao_qtterapiasaldo08,
        sessao_obssessao08,
        sessao_terapiaid09,
        sessao_qtterapiaprev09,
        sessao_qtterapiacon09,
        sessao_qtterapiasaldo09,
        sessao_obssessao09,
        sessao_terapiaid10,
        sessao_qtterapiaprev10,
        sessao_qtterapiacon10,
        sessao_qtterapiasaldo10,
        sessao_obssessao10,
        sessao_terapiaid11,
        sessao_qtterapiaprev11,
        sessao_qtterapiacon11,
        sessao_qtterapiasaldo11,
        sessao_obssessao11,
        sessao_terapiaid12,
        sessao_qtterapiaprev12,
        sessao_qtterapiacon12,
        sessao_qtterapiasaldo12,
        sessao_obssessao12,
        sessao_terapiaid13,
        sessao_qtterapiaprev13,
        sessao_qtterapiacon13,
        sessao_qtterapiasaldo13,
        sessao_obssessao13,
        sessao_terapiaid14,
        sessao_qtterapiaprev14,
        sessao_qtterapiacon14,
        sessao_qtterapiasaldo14,
        sessao_obssessao14,
        sessao_terapiaid15,
        sessao_qtterapiaprev15,
        sessao_qtterapiacon15,
        sessao_qtterapiasaldo15,
        sessao_obssessao15,
        sessao_terapiaid16,
        sessao_qtterapiaprev16,
        sessao_qtterapiacon16,
        sessao_qtterapiasaldo16,
        sessao_obssessao16,
        sessao_terapiaid17,
        sessao_qtterapiaprev17,
        sessao_qtterapiacon17,
        sessao_qtterapiasaldo17,
        sessao_obssessao17,
        sessao_terapiaid18,
        sessao_qtterapiaprev18,
        sessao_qtterapiacon18,
        sessao_qtterapiasaldo18,
        sessao_obssessao18,
        sessao_terapiaid19,
        sessao_qtterapiaprev19,
        sessao_qtterapiacon19,
        sessao_qtterapiasaldo19,
        sessao_obssessao19,
        sessao_terapiaid20,
        sessao_qtterapiaprev20,
        sessao_qtterapiacon20,
        sessao_qtterapiasaldo20,
        sessao_obssessao20,
        sessao_terapiaid21,
        sessao_qtterapiaprev21,
        sessao_qtterapiacon21,
        sessao_qtterapiasaldo21,
        sessao_obssessao21,
        sessao_terapiaid22,
        sessao_qtterapiaprev22,
        sessao_qtterapiacon22,
        sessao_qtterapiasaldo22,
        sessao_obssessao22,
        sessao_terapiaid23,
        sessao_qtterapiaprev23,
        sessao_qtterapiacon23,
        sessao_qtterapiasaldo23,
        sessao_obssessao23,
        sessao_terapiaid24,
        sessao_qtterapiaprev24,
        sessao_qtterapiacon24,
        sessao_qtterapiasaldo24,
        sessao_obssessao24,
        sessao_terapiaid25,
        sessao_qtterapiaprev25,
        sessao_qtterapiacon25,
        sessao_qtterapiasaldo25,
        sessao_obssessao25,
        //Atributos de controle
        sessao_usuidcad,
        sessao_usuidedi,
        sessao_datacad,
        sessao_dataedi

        ){
            this.sessao_beneid = sessao_beneid,
            this.sessao_convid = sessao_convid,
            this.sessao_terapiaid01 = sessao_terapiaid01,
            this.sessao_qtterapiaprev01 = sessao_qtterapiaprev01,
            this.sessao_qtterapiacon01 = sessao_qtterapiacon01,
            this.sessao_qtterapiasaldo01 = sessao_qtterapiasaldo01,
            this.sessao_obssessao01 = sessao_obssessao01,
            this.sessao_terapiaid02 = sessao_terapiaid02,
            this.sessao_qtterapiaprev02 = sessao_qtterapiaprev02,
            this.sessao_qtterapiacon02 = sessao_qtterapiacon02,
            this.sessao_qtterapiasaldo02 = sessao_qtterapiasaldo02,
            this.sessao_obssessao02 = sessao_obssessao02,
            this.sessao_terapiaid03 = sessao_terapiaid03,
            this.sessao_qtterapiaprev03 = sessao_qtterapiaprev03,
            this.sessao_qtterapiacon03 = sessao_qtterapiacon03,
            this.sessao_qtterapiasaldo03 = sessao_qtterapiasaldo03,
            this.sessao_obssessao03 = sessao_obssessao03,
            this.sessao_terapiaid04 = sessao_terapiaid04,
            this.sessao_qtterapiaprev04 = sessao_qtterapiaprev04,
            this.sessao_qtterapiacon04 = sessao_qtterapiacon04,
            this.sessao_qtterapiasaldo04 = sessao_qtterapiasaldo04,
            this.sessao_obssessao04 = sessao_obssessao04,
            this.sessao_terapiaid05 = sessao_terapiaid05,
            this.sessao_qtterapiaprev05 = sessao_qtterapiaprev05,
            this.sessao_qtterapiacon05 = sessao_qtterapiacon05,
            this.sessao_qtterapiasaldo05 = sessao_qtterapiasaldo05,
            this.sessao_obssessao05 = sessao_obssessao05,
            this.sessao_terapiaid06 = sessao_terapiaid06,
            this.sessao_qtterapiaprev06 = sessao_qtterapiaprev06,
            this.sessao_qtterapiacon06 = sessao_qtterapiacon06,
            this.sessao_qtterapiasaldo06 = sessao_qtterapiasaldo06,
            this.sessao_obssessao06 = sessao_obssessao06,
            this.sessao_terapiaid07 = sessao_terapiaid07,
            this.sessao_qtterapiaprev07 = sessao_qtterapiaprev07,
            this.sessao_qtterapiacon07 = sessao_qtterapiacon07,
            this.sessao_qtterapiasaldo07 = sessao_qtterapiasaldo07,
            this.sessao_obssessao07 = sessao_obssessao07,
            this.sessao_terapiaid08 = sessao_terapiaid08,
            this.sessao_qtterapiaprev08 = sessao_qtterapiaprev08,
            this.sessao_qtterapiacon08 = sessao_qtterapiacon08,
            this.sessao_qtterapiasaldo08 = sessao_qtterapiasaldo08,
            this.sessao_obssessao08 = sessao_obssessao08,
            this.sessao_terapiaid09 = sessao_terapiaid09,
            this.sessao_qtterapiaprev09 = sessao_qtterapiaprev09,
            this.sessao_qtterapiacon09 = sessao_qtterapiacon09,
            this.sessao_qtterapiasaldo09 = sessao_qtterapiasaldo09,
            this.sessao_obssessao09 = sessao_obssessao09,
            this.sessao_terapiaid10 = sessao_terapiaid10,
            this.sessao_qtterapiaprev10 = sessao_qtterapiaprev10,
            this.sessao_qtterapiacon10 = sessao_qtterapiacon10,
            this.sessao_qtterapiasaldo10 = sessao_qtterapiasaldo10,
            this.sessao_obssessao10 = sessao_obssessao10,
            this.sessao_terapiaid11 = sessao_terapiaid11,
            this.sessao_qtterapiaprev11 = sessao_qtterapiaprev11,
            this.sessao_qtterapiacon11 = sessao_qtterapiacon11,
            this.sessao_qtterapiasaldo11 = sessao_qtterapiasaldo11,
            this.sessao_obssessao11 = sessao_obssessao11,
            this.sessao_terapiaid12 = sessao_terapiaid12,
            this.sessao_qtterapiaprev12 = sessao_qtterapiaprev12,
            this.sessao_qtterapiacon12 = sessao_qtterapiacon12,
            this.sessao_qtterapiasaldo12 = sessao_qtterapiasaldo12,
            this.sessao_obssessao12 = sessao_obssessao12,
            this.sessao_terapiaid13 = sessao_terapiaid13,
            this.sessao_qtterapiaprev13 = sessao_qtterapiaprev13,
            this.sessao_qtterapiacon13 = sessao_qtterapiacon13,
            this.sessao_qtterapiasaldo13 = sessao_qtterapiasaldo13,
            this.sessao_obssessao13 = sessao_obssessao13,
            this.sessao_terapiaid14 = sessao_terapiaid14,
            this.sessao_qtterapiaprev14 = sessao_qtterapiaprev14,
            this.sessao_qtterapiacon14 = sessao_qtterapiacon14,
            this.sessao_qtterapiasaldo14 = sessao_qtterapiasaldo14,
            this.sessao_obssessao14 = sessao_obssessao14,
            this.sessao_terapiaid15 = sessao_terapiaid15,
            this.sessao_qtterapiaprev15 = sessao_qtterapiaprev15,
            this.sessao_qtterapiacon15 = sessao_qtterapiacon15,
            this.sessao_qtterapiasaldo15 = sessao_qtterapiasaldo15,
            this.sessao_obssessao15 = sessao_obssessao15,
            this.sessao_terapiaid16 = sessao_terapiaid16,
            this.sessao_qtterapiaprev16 = sessao_qtterapiaprev16,
            this.sessao_qtterapiacon16 = sessao_qtterapiacon16,
            this.sessao_qtterapiasaldo16 = sessao_qtterapiasaldo16,
            this.sessao_obssessao16 = sessao_obssessao16,
            this.sessao_terapiaid17 = sessao_terapiaid17,
            this.sessao_qtterapiaprev17 = sessao_qtterapiaprev17,
            this.sessao_qtterapiacon17 = sessao_qtterapiacon17,
            this.sessao_qtterapiasaldo17 = sessao_qtterapiasaldo17,
            this.sessao_obssessao17 = sessao_obssessao17,
            this.sessao_terapiaid18 = sessao_terapiaid18,
            this.sessao_qtterapiaprev18 = sessao_qtterapiaprev18,
            this.sessao_qtterapiacon18 = sessao_qtterapiacon18,
            this.sessao_qtterapiasaldo18 = sessao_qtterapiasaldo18,
            this.sessao_obssessao18 = sessao_obssessao18,
            this.sessao_terapiaid19 = sessao_terapiaid19,
            this.sessao_qtterapiaprev19 = sessao_qtterapiaprev19,
            this.sessao_qtterapiacon19 = sessao_qtterapiacon19,
            this.sessao_qtterapiasaldo19 = sessao_qtterapiasaldo19,
            this.sessao_obssessao19 = sessao_obssessao19,
            this.sessao_terapiaid20 = sessao_terapiaid20,
            this.sessao_qtterapiaprev20 = sessao_qtterapiaprev20,
            this.sessao_qtterapiacon20 = sessao_qtterapiacon20,
            this.sessao_qtterapiasaldo20 = sessao_qtterapiasaldo20,
            this.sessao_obssessao20 = sessao_obssessao20,
            this.sessao_terapiaid21 = sessao_terapiaid21,
            this.sessao_qtterapiaprev21 = sessao_qtterapiaprev21,
            this.sessao_qtterapiacon21 = sessao_qtterapiacon21,
            this.sessao_qtterapiasaldo21 = sessao_qtterapiasaldo21,
            this.sessao_obssessao21 = sessao_obssessao21,
            this.sessao_terapiaid22 = sessao_terapiaid22,
            this.sessao_qtterapiaprev22 = sessao_qtterapiaprev22,
            this.sessao_qtterapiacon22 = sessao_qtterapiacon22,
            this.sessao_qtterapiasaldo22 = sessao_qtterapiasaldo22,
            this.sessao_obssessao22 = sessao_obssessao22,
            this.sessao_terapiaid23 = sessao_terapiaid23,
            this.sessao_qtterapiaprev23 = sessao_qtterapiaprev23,
            this.sessao_qtterapiacon23 = sessao_qtterapiacon23,
            this.sessao_qtterapiasaldo23 = sessao_qtterapiasaldo23,
            this.sessao_obssessao23 = sessao_obssessao23,
            this.sessao_terapiaid24 = sessao_terapiaid24,
            this.sessao_qtterapiaprev24 = sessao_qtterapiaprev24,
            this.sessao_qtterapiacon24 = sessao_qtterapiacon24,
            this.sessao_qtterapiasaldo24 = sessao_qtterapiasaldo24,
            this.sessao_obssessao24 = sessao_obssessao24,
            this.sessao_terapiaid25 = sessao_terapiaid25,
            this.sessao_qtterapiaprev25 = sessao_qtterapiaprev25,
            this.sessao_qtterapiacon25 = sessao_qtterapiacon25,
            this.sessao_qtterapiasaldo25 = sessao_qtterapiasaldo25,
            this.sessao_obssessao25 = sessao_obssessao25,
            //Atributos de controle
            this.sessao_usuidcad = sessao_usuidcad,
            this.sessao_usuidedi = sessao_usuidedi,
            this.sessao_datacad = sessao_datacad,
            this.sessao_dataedi = sessao_dataedi

    }
}

SessaoSchema.loadClass(Sessao)
const SessaoModel = mongoose.model('tb_sessao', SessaoSchema)
module.exports = {SessaoModel,SessaoSchema,
    sessaoEditar: async (req, res) => {
        let dataAtual = new Date();
        let resultado;
        
        //Realiza Atualização
        await SessaoModel.findByIdAndUpdate(req.body.sessaoId, 
            {$set: {
                sessao_beneid : req.body.sessaoBeneid,
                sessao_convid : req.body.sessaoConvid,
                sessao_terapiaid01 : req.body.sessaoTerapiaid01,
                sessao_qtterapiaprev01 : req.body.sessaoQtterapiaprev01,
                sessao_qtterapiacon01 : req.body.sessaoQtterapiacon01,
                sessao_qtterapiasaldo01 : req.body.sessaoQtterapiasaldo01,
                sessao_obssessao01 : req.body.sessaoObssessao01,
                sessao_terapiaid02 : req.body.sessaoTerapiaid02,
                sessao_qtterapiaprev02 : req.body.sessaoQtterapiaprev02,
                sessao_qtterapiacon02 : req.body.sessaoQtterapiacon02,
                sessao_qtterapiasaldo02 : req.body.sessaoQtterapiasaldo02,
                sessao_obssessao02 : req.body.sessaoObssessao02,
                sessao_terapiaid03 : req.body.sessaoTerapiaid03,
                sessao_qtterapiaprev03 : req.body.sessaoQtterapiaprev03,
                sessao_qtterapiacon03 : req.body.sessaoQtterapiacon03,
                sessao_qtterapiasaldo03 : req.body.sessaoQtterapiasaldo03,
                sessao_obssessao03 : req.body.sessaoObssessao03,
                sessao_terapiaid04 : req.body.sessaoTerapiaid04,
                sessao_qtterapiaprev04 : req.body.sessaoQtterapiaprev04,
                sessao_qtterapiacon04 : req.body.sessaoQtterapiacon04,
                sessao_qtterapiasaldo04 : req.body.sessaoQtterapiasaldo04,
                sessao_obssessao04 : req.body.sessaoObssessao04,
                sessao_terapiaid05 : req.body.sessaoTerapiaid05,
                sessao_qtterapiaprev05 : req.body.sessaoQtterapiaprev05,
                sessao_qtterapiacon05 : req.body.sessaoQtterapiacon05,
                sessao_qtterapiasaldo05 : req.body.sessaoQtterapiasaldo05,
                sessao_obssessao05 : req.body.sessaoObssessao05,
                sessao_terapiaid06 : req.body.sessaoTerapiaid06,
                sessao_qtterapiaprev06 : req.body.sessaoQtterapiaprev06,
                sessao_qtterapiacon06 : req.body.sessaoQtterapiacon06,
                sessao_qtterapiasaldo06 : req.body.sessaoQtterapiasaldo06,
                sessao_obssessao06 : req.body.sessaoObssessao06,
                sessao_terapiaid07 : req.body.sessaoTerapiaid07,
                sessao_qtterapiaprev07 : req.body.sessaoQtterapiaprev07,
                sessao_qtterapiacon07 : req.body.sessaoQtterapiacon07,
                sessao_qtterapiasaldo07 : req.body.sessaoQtterapiasaldo07,
                sessao_obssessao07 : req.body.sessaoObssessao07,
                sessao_terapiaid08 : req.body.sessaoTerapiaid08,
                sessao_qtterapiaprev08 : req.body.sessaoQtterapiaprev08,
                sessao_qtterapiacon08 : req.body.sessaoQtterapiacon08,
                sessao_qtterapiasaldo08 : req.body.sessaoQtterapiasaldo08,
                sessao_obssessao08 : req.body.sessaoObssessao08,
                sessao_terapiaid09 : req.body.sessaoTerapiaid09,
                sessao_qtterapiaprev09 : req.body.sessaoQtterapiaprev09,
                sessao_qtterapiacon09 : req.body.sessaoQtterapiacon09,
                sessao_qtterapiasaldo09 : req.body.sessaoQtterapiasaldo09,
                sessao_obssessao09 : req.body.sessaoObssessao09,
                sessao_terapiaid10 : req.body.sessaoTerapiaid10,
                sessao_qtterapiaprev10 : req.body.sessaoQtterapiaprev10,
                sessao_qtterapiacon10 : req.body.sessaoQtterapiacon10,
                sessao_qtterapiasaldo10 : req.body.sessaoQtterapiasaldo10,
                sessao_obssessao10 : req.body.sessaoObssessao10,
                sessao_terapiaid11 : req.body.sessaoTerapiaid11,
                sessao_qtterapiaprev11 : req.body.sessaoQtterapiaprev11,
                sessao_qtterapiacon11 : req.body.sessaoQtterapiacon11,
                sessao_qtterapiasaldo11 : req.body.sessaoQtterapiasaldo11,
                sessao_obssessao11 : req.body.sessaoObssessao11,
                sessao_terapiaid12 : req.body.sessaoTerapiaid12,
                sessao_qtterapiaprev12 : req.body.sessaoQtterapiaprev12,
                sessao_qtterapiacon12 : req.body.sessaoQtterapiacon12,
                sessao_qtterapiasaldo12 : req.body.sessaoQtterapiasaldo12,
                sessao_obssessao12 : req.body.sessaoObssessao12,
                sessao_terapiaid13 : req.body.sessaoTerapiaid13,
                sessao_qtterapiaprev13 : req.body.sessaoQtterapiaprev13,
                sessao_qtterapiacon13 : req.body.sessaoQtterapiacon13,
                sessao_qtterapiasaldo13 : req.body.sessaoQtterapiasaldo13,
                sessao_obssessao13 : req.body.sessaoObssessao13,
                sessao_terapiaid14 : req.body.sessaoTerapiaid14,
                sessao_qtterapiaprev14 : req.body.sessaoQtterapiaprev14,
                sessao_qtterapiacon14 : req.body.sessaoQtterapiacon14,
                sessao_qtterapiasaldo14 : req.body.sessaoQtterapiasaldo14,
                sessao_obssessao14 : req.body.sessaoObssessao14,
                sessao_terapiaid15 : req.body.sessaoTerapiaid15,
                sessao_qtterapiaprev15 : req.body.sessaoQtterapiaprev15,
                sessao_qtterapiacon15 : req.body.sessaoQtterapiacon15,
                sessao_qtterapiasaldo15 : req.body.sessaoQtterapiasaldo15,
                sessao_obssessao15 : req.body.sessaoObssessao15,
                sessao_terapiaid16 : req.body.sessaoTerapiaid16,
                sessao_qtterapiaprev16 : req.body.sessaoQtterapiaprev16,
                sessao_qtterapiacon16 : req.body.sessaoQtterapiacon16,
                sessao_qtterapiasaldo16 : req.body.sessaoQtterapiasaldo16,
                sessao_obssessao16 : req.body.sessaoObssessao16,
                sessao_terapiaid17 : req.body.sessaoTerapiaid17,
                sessao_qtterapiaprev17 : req.body.sessaoQtterapiaprev17,
                sessao_qtterapiacon17 : req.body.sessaoQtterapiacon17,
                sessao_qtterapiasaldo17 : req.body.sessaoQtterapiasaldo17,
                sessao_obssessao17 : req.body.sessaoObssessao17,
                sessao_terapiaid18 : req.body.sessaoTerapiaid18,
                sessao_qtterapiaprev18 : req.body.sessaoQtterapiaprev18,
                sessao_qtterapiacon18 : req.body.sessaoQtterapiacon18,
                sessao_qtterapiasaldo18 : req.body.sessaoQtterapiasaldo18,
                sessao_obssessao18 : req.body.sessaoObssessao18,
                sessao_terapiaid19 : req.body.sessaoTerapiaid19,
                sessao_qtterapiaprev19 : req.body.sessaoQtterapiaprev19,
                sessao_qtterapiacon19 : req.body.sessaoQtterapiacon19,
                sessao_qtterapiasaldo19 : req.body.sessaoQtterapiasaldo19,
                sessao_obssessao19 : req.body.sessaoObssessao19,
                sessao_terapiaid20 : req.body.sessaoTerapiaid20,
                sessao_qtterapiaprev20 : req.body.sessaoQtterapiaprev20,
                sessao_qtterapiacon20 : req.body.sessaoQtterapiacon20,
                sessao_qtterapiasaldo20 : req.body.sessaoQtterapiasaldo20,
                sessao_obssessao20 : req.body.sessaoObssessao20,
                sessao_terapiaid21 : req.body.sessaoTerapiaid21,
                sessao_qtterapiaprev21 : req.body.sessaoQtterapiaprev21,
                sessao_qtterapiacon21 : req.body.sessaoQtterapiacon21,
                sessao_qtterapiasaldo21 : req.body.sessaoQtterapiasaldo21,
                sessao_obssessao21 : req.body.sessaoObssessao21,
                sessao_terapiaid22 : req.body.sessaoTerapiaid22,
                sessao_qtterapiaprev22 : req.body.sessaoQtterapiaprev22,
                sessao_qtterapiacon22 : req.body.sessaoQtterapiacon22,
                sessao_qtterapiasaldo22 : req.body.sessaoQtterapiasaldo22,
                sessao_obssessao22 : req.body.sessaoObssessao22,
                sessao_terapiaid23 : req.body.sessaoTerapiaid23,
                sessao_qtterapiaprev23 : req.body.sessaoQtterapiaprev23,
                sessao_qtterapiacon23 : req.body.sessaoQtterapiacon23,
                sessao_qtterapiasaldo23 : req.body.sessaoQtterapiasaldo23,
                sessao_obssessao23 : req.body.sessaoObssessao23,
                sessao_terapiaid24 : req.body.sessaoTerapiaid24,
                sessao_qtterapiaprev24 : req.body.sessaoQtterapiaprev24,
                sessao_qtterapiacon24 : req.body.sessaoQtterapiacon24,
                sessao_qtterapiasaldo24 : req.body.sessaoQtterapiasaldo24,
                sessao_obssessao24 : req.body.sessaoObssessao24,
                sessao_terapiaid25 : req.body.sessaoTerapiaid25,
                sessao_qtterapiaprev25 : req.body.sessaoQtterapiaprev25,
                sessao_qtterapiacon25 : req.body.sessaoQtterapiacon25,
                sessao_qtterapiasaldo25 : req.body.sessaoQtterapiasaldo25,
                sessao_obssessao25 : req.body.sessaoObssessao25,
                //Atributos de controle
                sessao_usuidedi : req.body.sessaoUsuidedi,
                sessao_dataedi : dataAtual.toISOString()
                
                
                }}
        ).then((res) =>{
            console.log("Salvo")
            resultado = true;
        }).catch((err) =>{
            console.log("erro mongo:")
            console.log(err)
            resultado = err;
            //res.redirect('admin/branco')
        })
        return resultado;
    },





    sessaoAdicionar: async (req,res) => {
        //Não Pode haver um Beneficiário com mesma terapia cadastrada Mais de uma Vez.
        //O campo de Integridade verifica se há mais de uma terapia igual para um mesmo beneficiário é impede o cadastro
        let sessaoExiste =  await SessaoModel.findOne({sessao_beneid: req.body.sessaoBeneid , sessao_terapiaid: req.body.sessaoTerapiaid});//quando não acha fica null
        let dataAtual = new Date();
        
        if(sessaoExiste){//se tiver null cai no else
            return "O nome da sessao já existe";
            //programar alert
        } else {
            console.log("sessaomodel");
            const newSessao = new SessaoModel({
                sessao_beneid : req.body.sessaoBeneid,
                sessao_convid : req.body.sessaoConvid,
                sessao_terapiaid01 : req.body.sessaoTerapiaid01,
                sessao_qtterapiaprev01 : req.body.sessaoQtterapiaprev01,
                sessao_qtterapiacon01 : req.body.sessaoQtterapiacon01,
                sessao_qtterapiasaldo01 : req.body.sessaoQtterapiasaldo01,
                sessao_obssessao01 : req.body.sessaoObssessao01,
                sessao_terapiaid02 : req.body.sessaoTerapiaid02,
                sessao_qtterapiaprev02 : req.body.sessaoQtterapiaprev02,
                sessao_qtterapiacon02 : req.body.sessaoQtterapiacon02,
                sessao_qtterapiasaldo02 : req.body.sessaoQtterapiasaldo02,
                sessao_obssessao02 : req.body.sessaoObssessao02,
                sessao_terapiaid03 : req.body.sessaoTerapiaid03,
                sessao_qtterapiaprev03 : req.body.sessaoQtterapiaprev03,
                sessao_qtterapiacon03 : req.body.sessaoQtterapiacon03,
                sessao_qtterapiasaldo03 : req.body.sessaoQtterapiasaldo03,
                sessao_obssessao03 : req.body.sessaoObssessao03,
                sessao_terapiaid04 : req.body.sessaoTerapiaid04,
                sessao_qtterapiaprev04 : req.body.sessaoQtterapiaprev04,
                sessao_qtterapiacon04 : req.body.sessaoQtterapiacon04,
                sessao_qtterapiasaldo04 : req.body.sessaoQtterapiasaldo04,
                sessao_obssessao04 : req.body.sessaoObssessao04,
                sessao_terapiaid05 : req.body.sessaoTerapiaid05,
                sessao_qtterapiaprev05 : req.body.sessaoQtterapiaprev05,
                sessao_qtterapiacon05 : req.body.sessaoQtterapiacon05,
                sessao_qtterapiasaldo05 : req.body.sessaoQtterapiasaldo05,
                sessao_obssessao05 : req.body.sessaoObssessao05,
                sessao_terapiaid06 : req.body.sessaoTerapiaid06,
                sessao_qtterapiaprev06 : req.body.sessaoQtterapiaprev06,
                sessao_qtterapiacon06 : req.body.sessaoQtterapiacon06,
                sessao_qtterapiasaldo06 : req.body.sessaoQtterapiasaldo06,
                sessao_obssessao06 : req.body.sessaoObssessao06,
                sessao_terapiaid07 : req.body.sessaoTerapiaid07,
                sessao_qtterapiaprev07 : req.body.sessaoQtterapiaprev07,
                sessao_qtterapiacon07 : req.body.sessaoQtterapiacon07,
                sessao_qtterapiasaldo07 : req.body.sessaoQtterapiasaldo07,
                sessao_obssessao07 : req.body.sessaoObssessao07,
                sessao_terapiaid08 : req.body.sessaoTerapiaid08,
                sessao_qtterapiaprev08 : req.body.sessaoQtterapiaprev08,
                sessao_qtterapiacon08 : req.body.sessaoQtterapiacon08,
                sessao_qtterapiasaldo08 : req.body.sessaoQtterapiasaldo08,
                sessao_obssessao08 : req.body.sessaoObssessao08,
                sessao_terapiaid09 : req.body.sessaoTerapiaid09,
                sessao_qtterapiaprev09 : req.body.sessaoQtterapiaprev09,
                sessao_qtterapiacon09 : req.body.sessaoQtterapiacon09,
                sessao_qtterapiasaldo09 : req.body.sessaoQtterapiasaldo09,
                sessao_obssessao09 : req.body.sessaoObssessao09,
                sessao_terapiaid10 : req.body.sessaoTerapiaid10,
                sessao_qtterapiaprev10 : req.body.sessaoQtterapiaprev10,
                sessao_qtterapiacon10 : req.body.sessaoQtterapiacon10,
                sessao_qtterapiasaldo10 : req.body.sessaoQtterapiasaldo10,
                sessao_obssessao10 : req.body.sessaoObssessao10,
                sessao_terapiaid11 : req.body.sessaoTerapiaid11,
                sessao_qtterapiaprev11 : req.body.sessaoQtterapiaprev11,
                sessao_qtterapiacon11 : req.body.sessaoQtterapiacon11,
                sessao_qtterapiasaldo11 : req.body.sessaoQtterapiasaldo11,
                sessao_obssessao11 : req.body.sessaoObssessao11,
                sessao_terapiaid12 : req.body.sessaoTerapiaid12,
                sessao_qtterapiaprev12 : req.body.sessaoQtterapiaprev12,
                sessao_qtterapiacon12 : req.body.sessaoQtterapiacon12,
                sessao_qtterapiasaldo12 : req.body.sessaoQtterapiasaldo12,
                sessao_obssessao12 : req.body.sessaoObssessao12,
                sessao_terapiaid13 : req.body.sessaoTerapiaid13,
                sessao_qtterapiaprev13 : req.body.sessaoQtterapiaprev13,
                sessao_qtterapiacon13 : req.body.sessaoQtterapiacon13,
                sessao_qtterapiasaldo13 : req.body.sessaoQtterapiasaldo13,
                sessao_obssessao13 : req.body.sessaoObssessao13,
                sessao_terapiaid14 : req.body.sessaoTerapiaid14,
                sessao_qtterapiaprev14 : req.body.sessaoQtterapiaprev14,
                sessao_qtterapiacon14 : req.body.sessaoQtterapiacon14,
                sessao_qtterapiasaldo14 : req.body.sessaoQtterapiasaldo14,
                sessao_obssessao14 : req.body.sessaoObssessao14,
                sessao_terapiaid15 : req.body.sessaoTerapiaid15,
                sessao_qtterapiaprev15 : req.body.sessaoQtterapiaprev15,
                sessao_qtterapiacon15 : req.body.sessaoQtterapiacon15,
                sessao_qtterapiasaldo15 : req.body.sessaoQtterapiasaldo15,
                sessao_obssessao15 : req.body.sessaoObssessao15,
                sessao_terapiaid16 : req.body.sessaoTerapiaid16,
                sessao_qtterapiaprev16 : req.body.sessaoQtterapiaprev16,
                sessao_qtterapiacon16 : req.body.sessaoQtterapiacon16,
                sessao_qtterapiasaldo16 : req.body.sessaoQtterapiasaldo16,
                sessao_obssessao16 : req.body.sessaoObssessao16,
                sessao_terapiaid17 : req.body.sessaoTerapiaid17,
                sessao_qtterapiaprev17 : req.body.sessaoQtterapiaprev17,
                sessao_qtterapiacon17 : req.body.sessaoQtterapiacon17,
                sessao_qtterapiasaldo17 : req.body.sessaoQtterapiasaldo17,
                sessao_obssessao17 : req.body.sessaoObssessao17,
                sessao_terapiaid18 : req.body.sessaoTerapiaid18,
                sessao_qtterapiaprev18 : req.body.sessaoQtterapiaprev18,
                sessao_qtterapiacon18 : req.body.sessaoQtterapiacon18,
                sessao_qtterapiasaldo18 : req.body.sessaoQtterapiasaldo18,
                sessao_obssessao18 : req.body.sessaoObssessao18,
                sessao_terapiaid19 : req.body.sessaoTerapiaid19,
                sessao_qtterapiaprev19 : req.body.sessaoQtterapiaprev19,
                sessao_qtterapiacon19 : req.body.sessaoQtterapiacon19,
                sessao_qtterapiasaldo19 : req.body.sessaoQtterapiasaldo19,
                sessao_obssessao19 : req.body.sessaoObssessao19,
                sessao_terapiaid20 : req.body.sessaoTerapiaid20,
                sessao_qtterapiaprev20 : req.body.sessaoQtterapiaprev20,
                sessao_qtterapiacon20 : req.body.sessaoQtterapiacon20,
                sessao_qtterapiasaldo20 : req.body.sessaoQtterapiasaldo20,
                sessao_obssessao20 : req.body.sessaoObssessao20,
                sessao_terapiaid21 : req.body.sessaoTerapiaid21,
                sessao_qtterapiaprev21 : req.body.sessaoQtterapiaprev21,
                sessao_qtterapiacon21 : req.body.sessaoQtterapiacon21,
                sessao_qtterapiasaldo21 : req.body.sessaoQtterapiasaldo21,
                sessao_obssessao21 : req.body.sessaoObssessao21,
                sessao_terapiaid22 : req.body.sessaoTerapiaid22,
                sessao_qtterapiaprev22 : req.body.sessaoQtterapiaprev22,
                sessao_qtterapiacon22 : req.body.sessaoQtterapiacon22,
                sessao_qtterapiasaldo22 : req.body.sessaoQtterapiasaldo22,
                sessao_obssessao22 : req.body.sessaoObssessao22,
                sessao_terapiaid23 : req.body.sessaoTerapiaid23,
                sessao_qtterapiaprev23 : req.body.sessaoQtterapiaprev23,
                sessao_qtterapiacon23 : req.body.sessaoQtterapiacon23,
                sessao_qtterapiasaldo23 : req.body.sessaoQtterapiasaldo23,
                sessao_obssessao23 : req.body.sessaoObssessao23,
                sessao_terapiaid24 : req.body.sessaoTerapiaid24,
                sessao_qtterapiaprev24 : req.body.sessaoQtterapiaprev24,
                sessao_qtterapiacon24 : req.body.sessaoQtterapiacon24,
                sessao_qtterapiasaldo24 : req.body.sessaoQtterapiasaldo24,
                sessao_obssessao24 : req.body.sessaoObssessao24,
                sessao_terapiaid25 : req.body.sessaoTerapiaid25,
                sessao_qtterapiaprev25 : req.body.sessaoQtterapiaprev25,
                sessao_qtterapiacon25 : req.body.sessaoQtterapiacon25,
                sessao_qtterapiasaldo25 : req.body.sessaoQtterapiasaldo25,
                sessao_obssessao25 : req.body.sessaoObssessao25,
                //Atributos de controle
                sessao_usuidcad : req.body.sessaoUsuidcad,
                sessao_datacad : dataAtual.toISOString()
            });
            console.log("newSessao save");
            await newSessao.save().then(()=>{
                console.log("Cadastro realizado!");
                return true;
            }).catch((err) => {
                console.log(err)
                return err;
            });
        }
    }
};